"""Runtime loader for the static LSB menu catalog.

The catalog is generated by `lsb_extract.py` and lives at
`persistent/menu_catalog.json`. It contains everything we can mine
deterministically from LandSandBoat scripts:

  - homepoints[]:           every home point destination, indexed
                             by the option order the menu uses
  - conquest_outposts[]:    every region's outpost-warp destination
  - vendors{}:              per-NPC stock arrays
  - enums.zone:             zone-name -> id (lookup utility)
  - enums.region:           region-name -> id

This module exposes lookups in shapes the interact_director and
menu_judge consume:

  - homepoints_for_zone(zone_id) -> list[hp_record]
  - outpost_destinations()       -> list[outpost_record]
  - vendor_stock(npc, zone_id?)  -> list[stock_row] | None

The catalog is loaded once on first access and cached. Re-extract via
`python -m agent_core.lsb_extract --out <path>` to refresh.
"""
from __future__ import annotations

import json
from pathlib import Path
from threading import Lock
from typing import Any

from . import config as _config


_lock = Lock()
_cache: dict[str, Any] | None = None
_cache_path: Path | None = None


def _catalog_path(cfg: _config.Config) -> Path:
    return cfg.paths.persistent_dir(cfg.character).parent / 'menu_catalog.json'


def load(cfg: _config.Config) -> dict[str, Any]:
    """Load (and cache) the menu catalog. Empty dict if the file
    isn't present so callers can degrade gracefully (the agent still
    works without a catalog, just falls through to the LLM judge for
    every menu)."""
    global _cache, _cache_path
    path = _catalog_path(cfg)
    with _lock:
        if _cache is not None and _cache_path == path:
            return _cache
        if not path.exists():
            _cache = {}
            _cache_path = path
            return _cache
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
        except (json.JSONDecodeError, OSError):
            data = {}
        if not isinstance(data, dict):
            data = {}
        _cache = data
        _cache_path = path
        return _cache


def reload(cfg: _config.Config) -> dict[str, Any]:
    """Force a re-read from disk - useful after re-extracting LSB."""
    global _cache
    with _lock:
        _cache = None
    return load(cfg)


# ---- lookups ------------------------------------------------------


def homepoints_for_zone(cfg: _config.Config,
                        zone_id: int) -> list[dict[str, Any]]:
    """Every home point in the given zone, in menu order. The
    homepointData table is indexed 0..N globally; the option index
    the player picks at a home point's NPC menu is the SAME index
    in the global table (LSB iterates the table in order to render
    the destination list, but the visible list is filtered to the
    home points in the player's current home-point GROUP). For our
    purposes the per-zone filter is the right scope."""
    cat = load(cfg)
    out = []
    for hp in cat.get('homepoints') or []:
        if hp.get('zone_id') == zone_id:
            out.append(hp)
    return out


def homepoint_by_label(cfg: _config.Config,
                       label_substr: str) -> dict[str, Any] | None:
    """Find a home point by the trailing comment label, e.g.
    "Bastok Markets #1". Substring match; first-hit wins. Useful
    when the planner emits a home_point goal targeting a named
    HP rather than a zone."""
    needle = label_substr.strip().lower()
    if not needle:
        return None
    for hp in load(cfg).get('homepoints') or []:
        if needle in (hp.get('label') or '').lower():
            return hp
    return None


def outpost_destinations(cfg: _config.Config) -> list[dict[str, Any]]:
    """All conquest-outpost warp destinations, in region-id order.
    The menu order at any conquest overseer matches this list."""
    cat = load(cfg)
    rows = list(cat.get('conquest_outposts') or [])
    rows.sort(key=lambda r: r.get('region_id') or 0)
    return rows


def outpost_for_zone(cfg: _config.Config,
                     zone_id: int) -> dict[str, Any] | None:
    """Reverse lookup: which outpost row warps to this zone? Useful
    when the planner wants 'travel to West Ronfaure via outpost.'"""
    for op in outpost_destinations(cfg):
        if op.get('zone_id') == zone_id:
            return op
    return None


def vendor_stock(cfg: _config.Config,
                 npc_name: str,
                 zone_id: int | None = None) -> list[dict[str, Any]]:
    """Stock list for a named vendor NPC, in menu order. zone_id
    optional but recommended - some NPC names overlap across zones
    (e.g. 'Yagudo Avatar' might appear in multiple Yagudo zones)."""
    cat = load(cfg)
    vendors = cat.get('vendors') or {}
    # Try (zone, npc) key first.
    if zone_id is not None:
        zone_name = zone_name_by_id(cfg, zone_id)
        if zone_name:
            key = f'{zone_name}::{npc_name}'
            if key in vendors:
                return list(vendors[key].get('stock') or [])
    # Fall back to npc-name suffix match across all zones.
    npc_lc = npc_name.strip().lower()
    for k, v in vendors.items():
        if k.lower().endswith(f'::{npc_lc}'):
            return list(v.get('stock') or [])
    return []


def vendor_carries_item(cfg: _config.Config,
                        item_name: str,
                        zone_id: int | None = None) -> list[dict[str, Any]]:
    """Find every vendor whose stock contains the given item name.
    Returns [{vendor_key, zone_id, npc_name, index, price, fame_min}].
    Used by the planner: 'where can we buy X' -> list of vendors."""
    item_target = item_name.strip().upper().replace(' ', '_').replace("'", '')
    out: list[dict[str, Any]] = []
    for k, v in (load(cfg).get('vendors') or {}).items():
        if zone_id is not None and v.get('zone_id') != zone_id:
            continue
        for row in v.get('stock') or []:
            if (row.get('item_name') or '').upper() == item_target:
                out.append({
                    'vendor_key': k,
                    'zone_id':    v.get('zone_id'),
                    'zone_name':  v.get('zone_name'),
                    'npc_name':   v.get('npc_name'),
                    'index':      row.get('index'),
                    'price':      row.get('price'),
                    'fame_min':   row.get('fame_min'),
                })
                break
    return out


# ---- enum helpers -----------------------------------------------


def zone_id_by_name(cfg: _config.Config, name: str) -> int | None:
    """Resolve a zone name like 'WEST_RONFAURE' or 'West Ronfaure'."""
    enums = load(cfg).get('enums') or {}
    zones = enums.get('zone') or {}
    canon = name.strip().upper().replace(' ', '_').replace("'", '')
    return zones.get(canon)


def zone_name_by_id(cfg: _config.Config, zone_id: int) -> str | None:
    enums = load(cfg).get('enums') or {}
    zones = enums.get('zone') or {}
    for name, zid in zones.items():
        if zid == zone_id:
            return name
    return None


def region_name_by_id(cfg: _config.Config, region_id: int) -> str | None:
    enums = load(cfg).get('enums') or {}
    regions = enums.get('region') or {}
    for name, rid in regions.items():
        if rid == region_id:
            return name
    return None
