--[[
* mapper - zone_transitions.lua
*
* Auto-generated by gen_zone_transitions.py from LandSandBoat SQL data.
* DO NOT EDIT MANUALLY — regenerate with gen_zone_transitions.py.
*
* Coordinate system: Ashita LocalPosition (X=east, Y=south/north)
* Conversion from server space: local_x = pos_x,  local_y = pos_z
--]]

local M = {}

-- Zone display names indexed by zone ID
M.ZONE_NAMES = {
    [0] = "unknown",
    [1] = "Phanauet Channel",
    [2] = "Carpenters Landing",
    [3] = "Manaclipper",
    [4] = "Bibiki Bay",
    [5] = "Uleguerand Range",
    [6] = "Bearclaw Pinnacle",
    [7] = "Attohwa Chasm",
    [8] = "Boneyard Gully",
    [9] = "PsoXja",
    [10] = "The Shrouded Maw",
    [11] = "Oldton Movalpolos",
    [12] = "Newton Movalpolos",
    [13] = "Mine Shaft 2716",
    [14] = "Hall of Transference",
    [15] = "Abyssea-Konschtat",
    [16] = "Promyvion-Holla",
    [17] = "Spire of Holla",
    [18] = "Promyvion-Dem",
    [19] = "Spire of Dem",
    [20] = "Promyvion-Mea",
    [21] = "Spire of Mea",
    [22] = "Promyvion-Vahzl",
    [23] = "Spire of Vahzl",
    [24] = "Lufaise Meadows",
    [25] = "Misareaux Coast",
    [26] = "Tavnazian Safehold",
    [27] = "Phomiuna Aqueducts",
    [28] = "Sacrarium",
    [29] = "Riverne-Site B01",
    [30] = "Riverne-Site A01",
    [31] = "Monarch Linn",
    [32] = "Sealions Den",
    [33] = "AlTaieu",
    [34] = "Grand Palace of HuXzoi",
    [35] = "The Garden of RuHmet",
    [36] = "Empyreal Paradox",
    [37] = "Temenos",
    [38] = "Apollyon",
    [39] = "Dynamis-Valkurm",
    [40] = "Dynamis-Buburimu",
    [41] = "Dynamis-Qufim",
    [42] = "Dynamis-Tavnazia",
    [43] = "Diorama Abdhaljs-Ghelsba",
    [44] = "Abdhaljs Isle-Purgonorgo",
    [45] = "Abyssea-Tahrongi",
    [46] = "Open sea route to Al Zahbi",
    [47] = "Open sea route to Mhaura",
    [48] = "Al Zahbi",
    [49] = "none",
    [50] = "Aht Urhgan Whitegate",
    [51] = "Wajaom Woodlands",
    [52] = "Bhaflau Thickets",
    [53] = "Nashmau",
    [54] = "Arrapago Reef",
    [55] = "Ilrusi Atoll",
    [56] = "Periqia",
    [57] = "Talacca Cove",
    [58] = "Silver Sea route to Nashmau",
    [59] = "Silver Sea route to Al Zahbi",
    [60] = "The Ashu Talif",
    [61] = "Mount Zhayolm",
    [62] = "Halvung",
    [63] = "Lebros Cavern",
    [64] = "Navukgo Execution Chamber",
    [65] = "Mamook",
    [66] = "Mamool Ja Training Grounds",
    [67] = "Jade Sepulcher",
    [68] = "Aydeewa Subterrane",
    [69] = "Leujaoam Sanctum",
    [70] = "Chocobo Circuit",
    [71] = "The Colosseum",
    [72] = "Alzadaal Undersea Ruins",
    [73] = "Zhayolm Remnants",
    [74] = "Arrapago Remnants",
    [75] = "Bhaflau Remnants",
    [76] = "Silver Sea Remnants",
    [77] = "Nyzul Isle",
    [78] = "Hazhalm Testing Grounds",
    [79] = "Caedarva Mire",
    [80] = "Southern San dOria [S]",
    [81] = "East Ronfaure [S]",
    [82] = "Jugner Forest [S]",
    [83] = "Vunkerl Inlet [S]",
    [84] = "Batallia Downs [S]",
    [85] = "La Vaule [S]",
    [86] = "Everbloom Hollow",
    [87] = "Bastok Markets [S]",
    [88] = "North Gustaberg [S]",
    [89] = "Grauberg [S]",
    [90] = "Pashhow Marshlands [S]",
    [91] = "Rolanberry Fields [S]",
    [92] = "Beadeaux [S]",
    [93] = "Ruhotz Silvermines",
    [94] = "Windurst Waters [S]",
    [95] = "West Sarutabaruta [S]",
    [96] = "Fort Karugo-Narugo [S]",
    [97] = "Meriphataud Mountains [S]",
    [98] = "Sauromugue Champaign [S]",
    [99] = "Castle Oztroja [S]",
    [100] = "West Ronfaure",
    [101] = "East Ronfaure",
    [102] = "La Theine Plateau",
    [103] = "Valkurm Dunes",
    [104] = "Jugner Forest",
    [105] = "Batallia Downs",
    [106] = "North Gustaberg",
    [107] = "South Gustaberg",
    [108] = "Konschtat Highlands",
    [109] = "Pashhow Marshlands",
    [110] = "Rolanberry Fields",
    [111] = "Beaucedine Glacier",
    [112] = "Xarcabard",
    [113] = "Cape Teriggan",
    [114] = "Eastern Altepa Desert",
    [115] = "West Sarutabaruta",
    [116] = "East Sarutabaruta",
    [117] = "Tahrongi Canyon",
    [118] = "Buburimu Peninsula",
    [119] = "Meriphataud Mountains",
    [120] = "Sauromugue Champaign",
    [121] = "The Sanctuary of ZiTah",
    [122] = "RoMaeve",
    [123] = "Yuhtunga Jungle",
    [124] = "Yhoator Jungle",
    [125] = "Western Altepa Desert",
    [126] = "Qufim Island",
    [127] = "Behemoths Dominion",
    [128] = "Valley of Sorrows",
    [129] = "Ghoyus Reverie",
    [130] = "RuAun Gardens",
    [131] = "Mordion Gaol",
    [132] = "Abyssea-La Theine",
    [133] = "Outer RaKaznar [U2]",
    [134] = "Dynamis-Beaucedine",
    [135] = "Dynamis-Xarcabard",
    [136] = "Beaucedine Glacier [S]",
    [137] = "Xarcabard [S]",
    [138] = "Castle Zvahl Baileys [S]",
    [139] = "Horlais Peak",
    [140] = "Ghelsba Outpost",
    [141] = "Fort Ghelsba",
    [142] = "Yughott Grotto",
    [143] = "Palborough Mines",
    [144] = "Waughroon Shrine",
    [145] = "Giddeus",
    [146] = "Balgas Dais",
    [147] = "Beadeaux",
    [148] = "Qulun Dome",
    [149] = "Davoi",
    [150] = "Monastic Cavern",
    [151] = "Castle Oztroja",
    [152] = "Altar Room",
    [153] = "The Boyahda Tree",
    [154] = "Dragons Aery",
    [155] = "Castle Zvahl Keep [S]",
    [156] = "Throne Room [S]",
    [157] = "Middle Delkfutts Tower",
    [158] = "Upper Delkfutts Tower",
    [159] = "Temple of Uggalepih",
    [160] = "Den of Rancor",
    [161] = "Castle Zvahl Baileys",
    [162] = "Castle Zvahl Keep",
    [163] = "Sacrificial Chamber",
    [164] = "Garlaige Citadel [S]",
    [165] = "Throne Room",
    [166] = "Ranguemont Pass",
    [167] = "Bostaunieux Oubliette",
    [168] = "Chamber of Oracles",
    [169] = "Toraimarai Canal",
    [170] = "Full Moon Fountain",
    [171] = "Crawlers Nest [S]",
    [172] = "Zeruhn Mines",
    [173] = "Korroloka Tunnel",
    [174] = "Kuftal Tunnel",
    [175] = "The Eldieme Necropolis [S]",
    [176] = "Sea Serpent Grotto",
    [177] = "VeLugannon Palace",
    [178] = "The Shrine of RuAvitau",
    [179] = "Stellar Fulcrum",
    [180] = "LaLoff Amphitheater",
    [181] = "The Celestial Nexus",
    [182] = "Walk of Echoes",
    [183] = "Maquette Abdhaljs-Legion A",
    [184] = "Lower Delkfutts Tower",
    [185] = "Dynamis-San dOria",
    [186] = "Dynamis-Bastok",
    [187] = "Dynamis-Windurst",
    [188] = "Dynamis-Jeuno",
    [189] = "Outer RaKaznar [U3]",
    [190] = "King Ranperres Tomb",
    [191] = "Dangruf Wadi",
    [192] = "Inner Horutoto Ruins",
    [193] = "Ordelles Caves",
    [194] = "Outer Horutoto Ruins",
    [195] = "The Eldieme Necropolis",
    [196] = "Gusgen Mines",
    [197] = "Crawlers Nest",
    [198] = "Maze of Shakhrami",
    [199] = "Residential Area",
    [200] = "Garlaige Citadel",
    [201] = "Cloister of Gales",
    [202] = "Cloister of Storms",
    [203] = "Cloister of Frost",
    [204] = "FeiYin",
    [205] = "Ifrits Cauldron",
    [206] = "QuBia Arena",
    [207] = "Cloister of Flames",
    [208] = "Quicksand Caves",
    [209] = "Cloister of Tremors",
    [210] = "GM Home",
    [211] = "Cloister of Tides",
    [212] = "Gustav Tunnel",
    [213] = "Labyrinth of Onzozo",
    [214] = "Residential Area",
    [215] = "Abyssea-Attohwa",
    [216] = "Abyssea-Misareaux",
    [217] = "Abyssea-Vunkerl",
    [218] = "Abyssea-Altepa",
    [219] = "Residential Area",
    [220] = "Ship bound for Selbina",
    [221] = "Ship bound for Mhaura",
    [222] = "Provenance",
    [223] = "San dOria-Jeuno Airship",
    [224] = "Bastok-Jeuno Airship",
    [225] = "Windurst-Jeuno Airship",
    [226] = "Kazham-Jeuno Airship",
    [227] = "Ship bound for Selbina Pirates",
    [228] = "Ship bound for Mhaura Pirates",
    [229] = "Throne Room [V]",
    [230] = "Southern San dOria",
    [231] = "Northern San dOria",
    [232] = "Port San dOria",
    [233] = "Chateau dOraguille",
    [234] = "Bastok Mines",
    [235] = "Bastok Markets",
    [236] = "Port Bastok",
    [237] = "Metalworks",
    [238] = "Windurst Waters",
    [239] = "Windurst Walls",
    [240] = "Port Windurst",
    [241] = "Windurst Woods",
    [242] = "Heavens Tower",
    [243] = "RuLude Gardens",
    [244] = "Upper Jeuno",
    [245] = "Lower Jeuno",
    [246] = "Port Jeuno",
    [247] = "Rabao",
    [248] = "Selbina",
    [249] = "Mhaura",
    [250] = "Kazham",
    [251] = "Hall of the Gods",
    [252] = "Norg",
    [253] = "Abyssea-Uleguerand",
    [254] = "Abyssea-Grauberg",
    [255] = "Abyssea-Empyreal Paradox",
    [256] = "Western Adoulin",
    [257] = "Eastern Adoulin",
    [258] = "Rala Waterways",
    [259] = "Rala Waterways U",
    [260] = "Yahse Hunting Grounds",
    [261] = "Ceizak Battlegrounds",
    [262] = "Foret de Hennetiel",
    [263] = "Yorcia Weald",
    [264] = "Yorcia Weald U",
    [265] = "Morimar Basalt Fields",
    [266] = "Marjami Ravine",
    [267] = "Kamihr Drifts",
    [268] = "Sih Gates",
    [269] = "Moh Gates",
    [270] = "Cirdas Caverns",
    [271] = "Cirdas Caverns U",
    [272] = "Dho Gates",
    [273] = "Woh Gates",
    [274] = "Outer RaKaznar",
    [275] = "Outer RaKaznar [U1]",
    [276] = "RaKaznar Inner Court",
    [277] = "RaKaznar Turris",
    [278] = "Gwora-Corridor",
    [279] = "Walk of Echoes [P2]",
    [280] = "Mog Garden",
    [281] = "Leafallia",
    [282] = "Mount Kamihr",
    [283] = "Silver Knife",
    [284] = "Celennia Memorial Library",
    [285] = "Feretory",
    [286] = "286",
    [287] = "Maquette Abdhaljs-Legion B",
    [288] = "Escha ZiTah",
    [289] = "Escha RuAun",
    [290] = "Desuetia Empyreal Paradox",
    [291] = "Reisenjima",
    [292] = "Reisenjima Henge",
    [293] = "Reisenjima Sanctorium",
    [294] = "Dynamis-San dOria [D]",
    [295] = "Dynamis-Bastok [D]",
    [296] = "Dynamis-Windurst [D]",
    [297] = "Dynamis-Jeuno [D]",
    [298] = "Walk of Echoes [P1]",
    [299] = "Gwora-Throne Room",
}

-- Zone ID lookup by normalised name (lowercase, no apostrophes)
M.ZONE_IDS = {
    ["286"] = 286,
    ["abdhaljs isle-purgonorgo"] = 44,
    ["abyssea-altepa"] = 218,
    ["abyssea-attohwa"] = 215,
    ["abyssea-empyreal paradox"] = 255,
    ["abyssea-grauberg"] = 254,
    ["abyssea-konschtat"] = 15,
    ["abyssea-la theine"] = 132,
    ["abyssea-misareaux"] = 216,
    ["abyssea-tahrongi"] = 45,
    ["abyssea-uleguerand"] = 253,
    ["abyssea-vunkerl"] = 217,
    ["aht urhgan whitegate"] = 50,
    ["al zahbi"] = 48,
    ["altaieu"] = 33,
    ["altar room"] = 152,
    ["alzadaal undersea ruins"] = 72,
    ["apollyon"] = 38,
    ["arrapago reef"] = 54,
    ["arrapago remnants"] = 74,
    ["attohwa chasm"] = 7,
    ["aydeewa subterrane"] = 68,
    ["balgas dais"] = 146,
    ["bastok markets"] = 235,
    ["bastok markets [s]"] = 87,
    ["bastok mines"] = 234,
    ["bastok-jeuno airship"] = 224,
    ["batallia downs"] = 105,
    ["batallia downs [s]"] = 84,
    ["beadeaux"] = 147,
    ["beadeaux [s]"] = 92,
    ["bearclaw pinnacle"] = 6,
    ["beaucedine glacier"] = 111,
    ["beaucedine glacier [s]"] = 136,
    ["behemoths dominion"] = 127,
    ["bhaflau remnants"] = 75,
    ["bhaflau thickets"] = 52,
    ["bibiki bay"] = 4,
    ["boneyard gully"] = 8,
    ["bostaunieux oubliette"] = 167,
    ["buburimu peninsula"] = 118,
    ["caedarva mire"] = 79,
    ["cape teriggan"] = 113,
    ["carpenters landing"] = 2,
    ["castle oztroja"] = 151,
    ["castle oztroja [s]"] = 99,
    ["castle zvahl baileys"] = 161,
    ["castle zvahl baileys [s]"] = 138,
    ["castle zvahl keep"] = 162,
    ["castle zvahl keep [s]"] = 155,
    ["ceizak battlegrounds"] = 261,
    ["celennia memorial library"] = 284,
    ["chamber of oracles"] = 168,
    ["chateau doraguille"] = 233,
    ["chocobo circuit"] = 70,
    ["cirdas caverns"] = 270,
    ["cirdas caverns u"] = 271,
    ["cloister of flames"] = 207,
    ["cloister of frost"] = 203,
    ["cloister of gales"] = 201,
    ["cloister of storms"] = 202,
    ["cloister of tides"] = 211,
    ["cloister of tremors"] = 209,
    ["crawlers nest"] = 197,
    ["crawlers nest [s]"] = 171,
    ["dangruf wadi"] = 191,
    ["davoi"] = 149,
    ["den of rancor"] = 160,
    ["desuetia empyreal paradox"] = 290,
    ["dho gates"] = 272,
    ["diorama abdhaljs-ghelsba"] = 43,
    ["dragons aery"] = 154,
    ["dynamis-bastok"] = 186,
    ["dynamis-bastok [d]"] = 295,
    ["dynamis-beaucedine"] = 134,
    ["dynamis-buburimu"] = 40,
    ["dynamis-jeuno"] = 188,
    ["dynamis-jeuno [d]"] = 297,
    ["dynamis-qufim"] = 41,
    ["dynamis-san doria"] = 185,
    ["dynamis-san doria [d]"] = 294,
    ["dynamis-tavnazia"] = 42,
    ["dynamis-valkurm"] = 39,
    ["dynamis-windurst"] = 187,
    ["dynamis-windurst [d]"] = 296,
    ["dynamis-xarcabard"] = 135,
    ["east ronfaure"] = 101,
    ["east ronfaure [s]"] = 81,
    ["east sarutabaruta"] = 116,
    ["eastern adoulin"] = 257,
    ["eastern altepa desert"] = 114,
    ["empyreal paradox"] = 36,
    ["escha ruaun"] = 289,
    ["escha zitah"] = 288,
    ["everbloom hollow"] = 86,
    ["feiyin"] = 204,
    ["feretory"] = 285,
    ["foret de hennetiel"] = 262,
    ["fort ghelsba"] = 141,
    ["fort karugo-narugo [s]"] = 96,
    ["full moon fountain"] = 170,
    ["gm home"] = 210,
    ["garlaige citadel"] = 200,
    ["garlaige citadel [s]"] = 164,
    ["ghelsba outpost"] = 140,
    ["ghoyus reverie"] = 129,
    ["giddeus"] = 145,
    ["grand palace of huxzoi"] = 34,
    ["grauberg [s]"] = 89,
    ["gusgen mines"] = 196,
    ["gustav tunnel"] = 212,
    ["gwora-corridor"] = 278,
    ["gwora-throne room"] = 299,
    ["hall of transference"] = 14,
    ["hall of the gods"] = 251,
    ["halvung"] = 62,
    ["hazhalm testing grounds"] = 78,
    ["heavens tower"] = 242,
    ["horlais peak"] = 139,
    ["ifrits cauldron"] = 205,
    ["ilrusi atoll"] = 55,
    ["inner horutoto ruins"] = 192,
    ["jade sepulcher"] = 67,
    ["jugner forest"] = 104,
    ["jugner forest [s]"] = 82,
    ["kamihr drifts"] = 267,
    ["kazham"] = 250,
    ["kazham-jeuno airship"] = 226,
    ["king ranperres tomb"] = 190,
    ["konschtat highlands"] = 108,
    ["korroloka tunnel"] = 173,
    ["kuftal tunnel"] = 174,
    ["la theine plateau"] = 102,
    ["la vaule [s]"] = 85,
    ["laloff amphitheater"] = 180,
    ["labyrinth of onzozo"] = 213,
    ["leafallia"] = 281,
    ["lebros cavern"] = 63,
    ["leujaoam sanctum"] = 69,
    ["lower delkfutts tower"] = 184,
    ["lower jeuno"] = 245,
    ["lufaise meadows"] = 24,
    ["mamook"] = 65,
    ["mamool ja training grounds"] = 66,
    ["manaclipper"] = 3,
    ["maquette abdhaljs-legion a"] = 183,
    ["maquette abdhaljs-legion b"] = 287,
    ["marjami ravine"] = 266,
    ["maze of shakhrami"] = 198,
    ["meriphataud mountains"] = 119,
    ["meriphataud mountains [s]"] = 97,
    ["metalworks"] = 237,
    ["mhaura"] = 249,
    ["middle delkfutts tower"] = 157,
    ["mine shaft 2716"] = 13,
    ["misareaux coast"] = 25,
    ["mog garden"] = 280,
    ["moh gates"] = 269,
    ["monarch linn"] = 31,
    ["monastic cavern"] = 150,
    ["mordion gaol"] = 131,
    ["morimar basalt fields"] = 265,
    ["mount kamihr"] = 282,
    ["mount zhayolm"] = 61,
    ["nashmau"] = 53,
    ["navukgo execution chamber"] = 64,
    ["newton movalpolos"] = 12,
    ["norg"] = 252,
    ["north gustaberg"] = 106,
    ["north gustaberg [s]"] = 88,
    ["northern san doria"] = 231,
    ["nyzul isle"] = 77,
    ["oldton movalpolos"] = 11,
    ["open sea route to al zahbi"] = 46,
    ["open sea route to mhaura"] = 47,
    ["ordelles caves"] = 193,
    ["outer horutoto ruins"] = 194,
    ["outer rakaznar"] = 274,
    ["outer rakaznar [u1]"] = 275,
    ["outer rakaznar [u2]"] = 133,
    ["outer rakaznar [u3]"] = 189,
    ["palborough mines"] = 143,
    ["pashhow marshlands"] = 109,
    ["pashhow marshlands [s]"] = 90,
    ["periqia"] = 56,
    ["phanauet channel"] = 1,
    ["phomiuna aqueducts"] = 27,
    ["port bastok"] = 236,
    ["port jeuno"] = 246,
    ["port san doria"] = 232,
    ["port windurst"] = 240,
    ["promyvion-dem"] = 18,
    ["promyvion-holla"] = 16,
    ["promyvion-mea"] = 20,
    ["promyvion-vahzl"] = 22,
    ["provenance"] = 222,
    ["psoxja"] = 9,
    ["qubia arena"] = 206,
    ["qufim island"] = 126,
    ["quicksand caves"] = 208,
    ["qulun dome"] = 148,
    ["rakaznar inner court"] = 276,
    ["rakaznar turris"] = 277,
    ["rabao"] = 247,
    ["rala waterways"] = 258,
    ["rala waterways u"] = 259,
    ["ranguemont pass"] = 166,
    ["reisenjima"] = 291,
    ["reisenjima henge"] = 292,
    ["reisenjima sanctorium"] = 293,
    ["residential area"] = 199,
    ["residential area"] = 214,
    ["residential area"] = 219,
    ["riverne-site a01"] = 30,
    ["riverne-site b01"] = 29,
    ["romaeve"] = 122,
    ["rolanberry fields"] = 110,
    ["rolanberry fields [s]"] = 91,
    ["ruaun gardens"] = 130,
    ["rulude gardens"] = 243,
    ["ruhotz silvermines"] = 93,
    ["sacrarium"] = 28,
    ["sacrificial chamber"] = 163,
    ["san doria-jeuno airship"] = 223,
    ["sauromugue champaign"] = 120,
    ["sauromugue champaign [s]"] = 98,
    ["sea serpent grotto"] = 176,
    ["sealions den"] = 32,
    ["selbina"] = 248,
    ["ship bound for mhaura"] = 221,
    ["ship bound for mhaura pirates"] = 228,
    ["ship bound for selbina"] = 220,
    ["ship bound for selbina pirates"] = 227,
    ["sih gates"] = 268,
    ["silver knife"] = 283,
    ["silver sea remnants"] = 76,
    ["silver sea route to al zahbi"] = 59,
    ["silver sea route to nashmau"] = 58,
    ["south gustaberg"] = 107,
    ["southern san doria"] = 230,
    ["southern san doria [s]"] = 80,
    ["spire of dem"] = 19,
    ["spire of holla"] = 17,
    ["spire of mea"] = 21,
    ["spire of vahzl"] = 23,
    ["stellar fulcrum"] = 179,
    ["tahrongi canyon"] = 117,
    ["talacca cove"] = 57,
    ["tavnazian safehold"] = 26,
    ["temenos"] = 37,
    ["temple of uggalepih"] = 159,
    ["the ashu talif"] = 60,
    ["the boyahda tree"] = 153,
    ["the celestial nexus"] = 181,
    ["the colosseum"] = 71,
    ["the eldieme necropolis"] = 195,
    ["the eldieme necropolis [s]"] = 175,
    ["the garden of ruhmet"] = 35,
    ["the sanctuary of zitah"] = 121,
    ["the shrine of ruavitau"] = 178,
    ["the shrouded maw"] = 10,
    ["throne room"] = 165,
    ["throne room [s]"] = 156,
    ["throne room [v]"] = 229,
    ["toraimarai canal"] = 169,
    ["uleguerand range"] = 5,
    ["upper delkfutts tower"] = 158,
    ["upper jeuno"] = 244,
    ["valkurm dunes"] = 103,
    ["valley of sorrows"] = 128,
    ["velugannon palace"] = 177,
    ["vunkerl inlet [s]"] = 83,
    ["wajaom woodlands"] = 51,
    ["walk of echoes"] = 182,
    ["walk of echoes [p1]"] = 298,
    ["walk of echoes [p2]"] = 279,
    ["waughroon shrine"] = 144,
    ["west ronfaure"] = 100,
    ["west sarutabaruta"] = 115,
    ["west sarutabaruta [s]"] = 95,
    ["western adoulin"] = 256,
    ["western altepa desert"] = 125,
    ["windurst walls"] = 239,
    ["windurst waters"] = 238,
    ["windurst waters [s]"] = 94,
    ["windurst woods"] = 241,
    ["windurst-jeuno airship"] = 225,
    ["woh gates"] = 273,
    ["xarcabard"] = 112,
    ["xarcabard [s]"] = 137,
    ["yahse hunting grounds"] = 260,
    ["yhoator jungle"] = 124,
    ["yorcia weald"] = 263,
    ["yorcia weald u"] = 264,
    ["yughott grotto"] = 142,
    ["yuhtunga jungle"] = 123,
    ["zeruhn mines"] = 172,
    ["zhayolm remnants"] = 73,
    ["none"] = 49,
    ["unknown"] = 0,
}

-- Autotranslate lookup: AT_LOOKUP[group*256+msg] = zone_id
-- Use resolve_zone() instead of accessing directly.
M.AT_LOOKUP = {
    [0x1401] = 104,  -- group=0x14 msg=0x01
    [0x1402] = 105,  -- group=0x14 msg=0x02
    [0x1403] = 193,  -- group=0x14 msg=0x03
    [0x1404] = 152,  -- group=0x14 msg=0x04
    [0x1406] = 246,  -- group=0x14 msg=0x06
    [0x1407] = 110,  -- group=0x14 msg=0x07
    [0x1408] = 126,  -- group=0x14 msg=0x08
    [0x1409] = 252,  -- group=0x14 msg=0x09
    [0x140A] = 127,  -- group=0x14 msg=0x0A
    [0x140B] = 158,  -- group=0x14 msg=0x0B
    [0x140C] = 157,  -- group=0x14 msg=0x0C
    [0x140D] = 184,  -- group=0x14 msg=0x0D
    [0x140E] = 245,  -- group=0x14 msg=0x0E
    [0x140F] = 101,  -- group=0x14 msg=0x0F
    [0x1411] = 100,  -- group=0x14 msg=0x11
    [0x1413] = 243,  -- group=0x14 msg=0x13
    [0x1414] = 200,  -- group=0x14 msg=0x14
    [0x1415] = 198,  -- group=0x14 msg=0x15
    [0x1416] = 118,  -- group=0x14 msg=0x16
    [0x1417] = 117,  -- group=0x14 msg=0x17
    [0x1418] = 115,  -- group=0x14 msg=0x18
    [0x1419] = 146,  -- group=0x14 msg=0x19
    [0x141A] = 144,  -- group=0x14 msg=0x1A
    [0x141B] = 194,  -- group=0x14 msg=0x1B
    [0x141C] = 192,  -- group=0x14 msg=0x1C
    [0x141D] = 169,  -- group=0x14 msg=0x1D
    [0x141E] = 249,  -- group=0x14 msg=0x1E
    [0x141F] = 141,  -- group=0x14 msg=0x1F
    [0x1420] = 119,  -- group=0x14 msg=0x20
    [0x1421] = 145,  -- group=0x14 msg=0x21
    [0x1422] = 233,  -- group=0x14 msg=0x22
    [0x1423] = 151,  -- group=0x14 msg=0x23
    [0x1424] = 111,  -- group=0x14 msg=0x24
    [0x1426] = 161,  -- group=0x14 msg=0x26
    [0x1427] = 116,  -- group=0x14 msg=0x27
    [0x1428] = 148,  -- group=0x14 msg=0x28
    [0x1429] = 250,  -- group=0x14 msg=0x29
    [0x142A] = 147,  -- group=0x14 msg=0x2A
    [0x142B] = 109,  -- group=0x14 msg=0x2B
    [0x142C] = 197,  -- group=0x14 msg=0x2C
    [0x142D] = 166,  -- group=0x14 msg=0x2D
    [0x142E] = 120,  -- group=0x14 msg=0x2E
    [0x142F] = 237,  -- group=0x14 msg=0x2F
    [0x1430] = 231,  -- group=0x14 msg=0x30
    [0x1431] = 247,  -- group=0x14 msg=0x31
    [0x1432] = 167,  -- group=0x14 msg=0x32
    [0x1433] = 213,  -- group=0x14 msg=0x33
    [0x1434] = 212,  -- group=0x14 msg=0x34
    [0x1435] = 160,  -- group=0x14 msg=0x35
    [0x1436] = 159,  -- group=0x14 msg=0x36
    [0x1437] = 154,  -- group=0x14 msg=0x37
    [0x1438] = 241,  -- group=0x14 msg=0x38
    [0x1439] = 163,  -- group=0x14 msg=0x39
    [0x143A] = 238,  -- group=0x14 msg=0x3A
    [0x143B] = 168,  -- group=0x14 msg=0x3B
    [0x143C] = 236,  -- group=0x14 msg=0x3C
    [0x143D] = 113,  -- group=0x14 msg=0x3D
    [0x143E] = 114,  -- group=0x14 msg=0x3E
    [0x143F] = 121,  -- group=0x14 msg=0x3F
    [0x1440] = 123,  -- group=0x14 msg=0x40
    [0x1441] = 124,  -- group=0x14 msg=0x41
    [0x1442] = 125,  -- group=0x14 msg=0x42
    [0x1443] = 128,  -- group=0x14 msg=0x43
    [0x1444] = 153,  -- group=0x14 msg=0x44
    [0x1445] = 240,  -- group=0x14 msg=0x45
    [0x1446] = 234,  -- group=0x14 msg=0x46
    [0x144A] = 204,  -- group=0x14 msg=0x4A
    [0x144C] = 230,  -- group=0x14 msg=0x4C
    [0x144D] = 112,  -- group=0x14 msg=0x4D
    [0x144E] = 244,  -- group=0x14 msg=0x4E
    [0x1450] = 162,  -- group=0x14 msg=0x50
    [0x1451] = 102,  -- group=0x14 msg=0x51
    [0x1452] = 232,  -- group=0x14 msg=0x52
    [0x1454] = 239,  -- group=0x14 msg=0x54
    [0x1455] = 242,  -- group=0x14 msg=0x55
    [0x1456] = 235,  -- group=0x14 msg=0x56
    [0x1457] = 208,  -- group=0x14 msg=0x57
    [0x1458] = 205,  -- group=0x14 msg=0x58
    [0x1459] = 176,  -- group=0x14 msg=0x59
    [0x145A] = 174,  -- group=0x14 msg=0x5A
    [0x145B] = 173,  -- group=0x14 msg=0x5B
    [0x145C] = 170,  -- group=0x14 msg=0x5C
    [0x145D] = 165,  -- group=0x14 msg=0x5D
    [0x145E] = 142,  -- group=0x14 msg=0x5E
    [0x145F] = 248,  -- group=0x14 msg=0x5F
    [0x1460] = 103,  -- group=0x14 msg=0x60
    [0x1461] = 172,  -- group=0x14 msg=0x61
    [0x1462] = 191,  -- group=0x14 msg=0x62
    [0x1463] = 107,  -- group=0x14 msg=0x63
    [0x1464] = 106,  -- group=0x14 msg=0x64
    [0x1465] = 139,  -- group=0x14 msg=0x65
    [0x1466] = 143,  -- group=0x14 msg=0x66
    [0x1467] = 196,  -- group=0x14 msg=0x67
    [0x1468] = 149,  -- group=0x14 msg=0x68
    [0x1469] = 108,  -- group=0x14 msg=0x69
    [0x146A] = 195,  -- group=0x14 msg=0x6A
    [0x146B] = 206,  -- group=0x14 msg=0x6B
    [0x146C] = 140,  -- group=0x14 msg=0x6C
    [0x146D] = 150,  -- group=0x14 msg=0x6D
    [0x146E] = 190,  -- group=0x14 msg=0x6E
    [0x146F] = 130,  -- group=0x14 msg=0x6F
    [0x1471] = 177,  -- group=0x14 msg=0x71
    [0x1472] = 178,  -- group=0x14 msg=0x72
    [0x1473] = 180,  -- group=0x14 msg=0x73
    [0x1474] = 181,  -- group=0x14 msg=0x74
    [0x1475] = 202,  -- group=0x14 msg=0x75
    [0x1476] = 209,  -- group=0x14 msg=0x76
    [0x1477] = 201,  -- group=0x14 msg=0x77
    [0x1478] = 207,  -- group=0x14 msg=0x78
    [0x1479] = 211,  -- group=0x14 msg=0x79
    [0x147A] = 203,  -- group=0x14 msg=0x7A
    [0x147B] = 251,  -- group=0x14 msg=0x7B
    [0x147D] = 122,  -- group=0x14 msg=0x7D
    [0x147E] = 185,  -- group=0x14 msg=0x7E
    [0x147F] = 186,  -- group=0x14 msg=0x7F
    [0x1480] = 187,  -- group=0x14 msg=0x80
    [0x1481] = 188,  -- group=0x14 msg=0x81
    [0x1482] = 134,  -- group=0x14 msg=0x82
    [0x1483] = 135,  -- group=0x14 msg=0x83
    [0x1484] = 3,  -- group=0x14 msg=0x84
    [0x1485] = 4,  -- group=0x14 msg=0x85
    [0x1486] = 7,  -- group=0x14 msg=0x86
    [0x1487] = 8,  -- group=0x14 msg=0x87
    [0x1488] = 9,  -- group=0x14 msg=0x88
    [0x1489] = 10,  -- group=0x14 msg=0x89
    [0x148A] = 5,  -- group=0x14 msg=0x8A
    [0x148B] = 6,  -- group=0x14 msg=0x8B
    [0x148C] = 11,  -- group=0x14 msg=0x8C
    [0x148D] = 12,  -- group=0x14 msg=0x8D
    [0x148E] = 13,  -- group=0x14 msg=0x8E
    [0x148F] = 26,  -- group=0x14 msg=0x8F
    [0x1490] = 24,  -- group=0x14 msg=0x90
    [0x1491] = 25,  -- group=0x14 msg=0x91
    [0x1492] = 32,  -- group=0x14 msg=0x92
    [0x1493] = 27,  -- group=0x14 msg=0x93
    [0x1494] = 28,  -- group=0x14 msg=0x94
    [0x1496] = 29,  -- group=0x14 msg=0x96
    [0x1498] = 30,  -- group=0x14 msg=0x98
    [0x1499] = 31,  -- group=0x14 msg=0x99
    [0x149B] = 16,  -- group=0x14 msg=0x9B
    [0x149C] = 17,  -- group=0x14 msg=0x9C
    [0x149E] = 18,  -- group=0x14 msg=0x9E
    [0x149F] = 19,  -- group=0x14 msg=0x9F
    [0x14A0] = 20,  -- group=0x14 msg=0xA0
    [0x14A2] = 21,  -- group=0x14 msg=0xA2
    [0x14A3] = 22,  -- group=0x14 msg=0xA3
    [0x14A7] = 23,  -- group=0x14 msg=0xA7
    [0x14A9] = 1,  -- group=0x14 msg=0xA9
    [0x14AA] = 2,  -- group=0x14 msg=0xAA
    [0x14AB] = 14,  -- group=0x14 msg=0xAB
    [0x14AC] = 33,  -- group=0x14 msg=0xAC
    [0x14AD] = 34,  -- group=0x14 msg=0xAD
    [0x14AE] = 35,  -- group=0x14 msg=0xAE
    [0x14AF] = 43,  -- group=0x14 msg=0xAF
    [0x14B0] = 36,  -- group=0x14 msg=0xB0
    [0x14B1] = 37,  -- group=0x14 msg=0xB1
    [0x14B2] = 38,  -- group=0x14 msg=0xB2
    [0x14B3] = 179,  -- group=0x14 msg=0xB3
    [0x14B4] = 39,  -- group=0x14 msg=0xB4
    [0x14B5] = 40,  -- group=0x14 msg=0xB5
    [0x14B6] = 41,  -- group=0x14 msg=0xB6
    [0x14B7] = 42,  -- group=0x14 msg=0xB7
    [0x14B8] = 44,  -- group=0x14 msg=0xB8
    [0x14B9] = 46,  -- group=0x14 msg=0xB9
    [0x14BA] = 47,  -- group=0x14 msg=0xBA
    [0x14BB] = 48,  -- group=0x14 msg=0xBB
    [0x14BC] = 50,  -- group=0x14 msg=0xBC
    [0x14BD] = 51,  -- group=0x14 msg=0xBD
    [0x14BE] = 52,  -- group=0x14 msg=0xBE
    [0x14BF] = 53,  -- group=0x14 msg=0xBF
    [0x14C0] = 54,  -- group=0x14 msg=0xC0
    [0x14C1] = 55,  -- group=0x14 msg=0xC1
    [0x14C2] = 56,  -- group=0x14 msg=0xC2
    [0x14C3] = 57,  -- group=0x14 msg=0xC3
    [0x14C4] = 58,  -- group=0x14 msg=0xC4
    [0x14C5] = 59,  -- group=0x14 msg=0xC5
    [0x14C6] = 60,  -- group=0x14 msg=0xC6
    [0x14C7] = 61,  -- group=0x14 msg=0xC7
    [0x14C8] = 62,  -- group=0x14 msg=0xC8
    [0x14C9] = 63,  -- group=0x14 msg=0xC9
    [0x14CA] = 64,  -- group=0x14 msg=0xCA
    [0x14CB] = 65,  -- group=0x14 msg=0xCB
    [0x14CC] = 66,  -- group=0x14 msg=0xCC
    [0x14CD] = 67,  -- group=0x14 msg=0xCD
    [0x14CE] = 68,  -- group=0x14 msg=0xCE
    [0x14CF] = 69,  -- group=0x14 msg=0xCF
    [0x14D0] = 79,  -- group=0x14 msg=0xD0
    [0x14DA] = 78,  -- group=0x14 msg=0xDA
    [0x14DB] = 50,  -- group=0x14 msg=0xDB
    [0x14DD] = 72,  -- group=0x14 msg=0xDD
    [0x14DE] = 73,  -- group=0x14 msg=0xDE
    [0x14DF] = 74,  -- group=0x14 msg=0xDF
    [0x14E0] = 75,  -- group=0x14 msg=0xE0
    [0x14E1] = 76,  -- group=0x14 msg=0xE1
    [0x14E2] = 77,  -- group=0x14 msg=0xE2
    [0x270F] = 70,  -- group=0x27 msg=0x0F
    [0x2710] = 71,  -- group=0x27 msg=0x10
    [0x2711] = 80,  -- group=0x27 msg=0x11
    [0x2712] = 274,  -- group=0x27 msg=0x12
    [0x2713] = 81,  -- group=0x27 msg=0x13
    [0x2715] = 82,  -- group=0x27 msg=0x15
    [0x2717] = 84,  -- group=0x27 msg=0x17
    [0x2719] = 86,  -- group=0x27 msg=0x19
    [0x271A] = 175,  -- group=0x27 msg=0x1A
    [0x271B] = 289,  -- group=0x27 msg=0x1B
    [0x271C] = 87,  -- group=0x27 msg=0x1C
    [0x271D] = 291,  -- group=0x27 msg=0x1D
    [0x271E] = 88,  -- group=0x27 msg=0x1E
    [0x2720] = 89,  -- group=0x27 msg=0x20
    [0x2722] = 93,  -- group=0x27 msg=0x22
    [0x2723] = 83,  -- group=0x27 msg=0x23
    [0x2725] = 90,  -- group=0x27 msg=0x25
    [0x2727] = 91,  -- group=0x27 msg=0x27
    [0x2729] = 171,  -- group=0x27 msg=0x29
    [0x272B] = 94,  -- group=0x27 msg=0x2B
    [0x272D] = 95,  -- group=0x27 msg=0x2D
    [0x272F] = 96,  -- group=0x27 msg=0x2F
    [0x2731] = 129,  -- group=0x27 msg=0x31
    [0x2732] = 97,  -- group=0x27 msg=0x32
    [0x2734] = 98,  -- group=0x27 msg=0x34
    [0x2736] = 164,  -- group=0x27 msg=0x36
    [0x273E] = 85,  -- group=0x27 msg=0x3E
    [0x2742] = 92,  -- group=0x27 msg=0x42
    [0x2744] = 99,  -- group=0x27 msg=0x44
    [0x2746] = 136,  -- group=0x27 msg=0x46
    [0x2748] = 137,  -- group=0x27 msg=0x48
    [0x274C] = 256,  -- group=0x27 msg=0x4C
    [0x274D] = 257,  -- group=0x27 msg=0x4D
    [0x274E] = 258,  -- group=0x27 msg=0x4E
    [0x274F] = 260,  -- group=0x27 msg=0x4F
    [0x2750] = 261,  -- group=0x27 msg=0x50
    [0x2751] = 262,  -- group=0x27 msg=0x51
    [0x2752] = 265,  -- group=0x27 msg=0x52
    [0x2753] = 268,  -- group=0x27 msg=0x53
    [0x2754] = 269,  -- group=0x27 msg=0x54
    [0x2755] = 270,  -- group=0x27 msg=0x55
    [0x2756] = 263,  -- group=0x27 msg=0x56
    [0x2757] = 266,  -- group=0x27 msg=0x57
    [0x2758] = 272,  -- group=0x27 msg=0x58
    [0x2759] = 284,  -- group=0x27 msg=0x59
    [0x275A] = 280,  -- group=0x27 msg=0x5A
    [0x275B] = 285,  -- group=0x27 msg=0x5B
    [0x275C] = 267,  -- group=0x27 msg=0x5C
    [0x275D] = 273,  -- group=0x27 msg=0x5D
}

-- Zone exits: EXITS[from_zone] = { {fx, fy, to_zone, tx, ty}, ... }
-- fx/fy = Ashita LocalPosition of the zone line trigger in from_zone
-- tx/ty = Ashita LocalPosition of arrival in to_zone
M.EXITS = {
    [2] = {
        {fx=0.786, fy=-819.851, to_zone=104, tx=341.844, ty=15.117},
        {fx=-420.264, fy=-560.076, to_zone=104, tx=-536.152, ty=336.587},
        {fx=-479.706, fy=672.851, to_zone=231, tx=-127.472, ty=195.478},
    },
    [4] = {
        {fx=673.803, fy=911.899, to_zone=118, tx=-276.529, ty=-324.519},
    },
    [5] = {
        {fx=-299.951, fy=-605.658, to_zone=112, tx=-136.287, ty=137.302},
        {fx=360.102, fy=-59.900, to_zone=6, tx=-679.796, ty=-539.992},
        {fx=420.134, fy=196.059, to_zone=6, tx=-819.917, ty=-82.521},
        {fx=59.998, fy=438.236, to_zone=6, tx=-795.490, ty=619.960},
        {fx=81.956, fy=179.876, to_zone=6, tx=119.997, ty=660.017},
        {fx=-200.076, fy=-60.120, to_zone=6, tx=-519.513, ty=-899.992},
        {fx=180.004, fy=121.050, to_zone=6, tx=-199.494, ty=-100.018},
    },
    [6] = {
        {fx=-677.021, fy=-540.013, to_zone=5, tx=363.025, ty=-59.903},
        {fx=-820.016, fy=-79.066, to_zone=5, tx=420.024, ty=198.498},
        {fx=-798.984, fy=620.020, to_zone=5, tx=60.015, ty=440.661},
        {fx=116.984, fy=660.044, to_zone=5, tx=79.508, ty=179.999},
        {fx=-523.003, fy=-899.966, to_zone=5, tx=-202.872, ty=-60.003},
        {fx=-203.003, fy=-99.965, to_zone=5, tx=179.994, ty=118.492},
    },
    [7] = {
        {fx=-167.101, fy=-261.720, to_zone=198, tx=-140.246, ty=160.709},
        {fx=-191.031, fy=336.814, to_zone=8, tx=-709.508, ty=456.241},
        {fx=-59.999, fy=242.986, to_zone=8, tx=627.536, ty=-695.364},
    },
    [8] = {
        {fx=-713.016, fy=458.011, to_zone=7, tx=-194.487, ty=338.704},
        {fx=630.969, fy=-696.831, to_zone=7, tx=-60.008, ty=239.497},
    },
    [9] = {
        {fx=404.925, fy=-20.008, to_zone=111, tx=242.292, ty=-20.005},
        {fx=-150.019, fy=50.043, to_zone=9, tx=-29.956, ty=212.521},
        {fx=220.053, fy=-274.952, to_zone=111, tx=60.008, ty=-357.679},
        {fx=-29.994, fy=210.000, to_zone=9, tx=-150.006, ty=47.486},
        {fx=180.013, fy=234.996, to_zone=111, tx=100.011, ty=157.695},
        {fx=-169.960, fy=9.953, to_zone=9, tx=-52.472, ty=170.008},
        {fx=-235.011, fy=-259.985, to_zone=111, tx=-197.717, ty=-219.995},
        {fx=-50.001, fy=169.955, to_zone=9, tx=-167.514, ty=9.987},
        {fx=-179.989, fy=-85.020, to_zone=111, tx=-19.996, ty=-42.291},
        {fx=-110.000, fy=30.007, to_zone=9, tx=12.486, ty=189.982},
        {fx=-299.999, fy=194.992, to_zone=111, tx=-339.974, ty=157.732},
        {fx=10.013, fy=189.982, to_zone=9, tx=-112.500, ty=30.015},
        {fx=14.978, fy=230.000, to_zone=9, tx=132.039, ty=69.998},
        {fx=-29.992, fy=-70.015, to_zone=9, tx=90.034, ty=52.504},
        {fx=135.039, fy=70.033, to_zone=9, tx=12.055, ty=229.969},
        {fx=89.974, fy=49.990, to_zone=9, tx=-30.181, ty=-67.082},
        {fx=135.050, fy=50.038, to_zone=9, tx=-49.986, ty=211.994},
        {fx=-60.000, fy=1.078, to_zone=10, tx=-300.000, ty=-219.928},
        {fx=-50.005, fy=214.952, to_zone=9, tx=131.994, ty=50.014},
        {fx=20.000, fy=-15.073, to_zone=10, tx=-179.683, ty=-296.610},
        {fx=-69.997, fy=214.950, to_zone=9, tx=30.009, ty=147.993},
        {fx=30.033, fy=144.979, to_zone=9, tx=-70.002, ty=211.975},
        {fx=14.955, fy=209.989, to_zone=9, tx=10.013, ty=147.996},
        {fx=10.013, fy=144.969, to_zone=9, tx=11.977, ty=210.019},
        {fx=15.029, fy=70.045, to_zone=9, tx=11.971, ty=-49.977},
        {fx=14.984, fy=-50.011, to_zone=9, tx=12.008, ty=70.000},
        {fx=15.027, fy=50.016, to_zone=9, tx=12.004, ty=-70.009},
        {fx=15.022, fy=-69.999, to_zone=9, tx=12.011, ty=49.986},
    },
    [10] = {
        {fx=-300.000, fy=-215.250, to_zone=9, tx=-60.000, ty=4.981},
        {fx=-180.020, fy=-291.250, to_zone=9, tx=20.000, ty=-11.005},
    },
    [11] = {
        {fx=-325.112, fy=-259.658, to_zone=106, tx=575.589, ty=692.864},
        {fx=-307.079, fy=-100.008, to_zone=106, tx=455.859, ty=733.027},
        {fx=-375.326, fy=464.797, to_zone=196, tx=100.007, ty=-237.441},
        {fx=73.896, fy=139.753, to_zone=12, tx=-261.858, ty=180.559},
        {fx=139.913, fy=-5.051, to_zone=12, tx=-220.031, ty=43.605},
        {fx=247.604, fy=-59.960, to_zone=12, tx=-141.883, ty=-19.373},
        {fx=199.017, fy=-140.129, to_zone=12, tx=-196.066, ty=-59.949},
        {fx=100.132, fy=-158.626, to_zone=12, tx=-260.004, ty=-123.785},
        {fx=-2.339, fy=-219.733, to_zone=12, tx=-356.944, ty=-179.974},
    },
    [12] = {
        {fx=-264.792, fy=180.392, to_zone=11, tx=70.956, ty=139.843},
        {fx=-219.790, fy=40.947, to_zone=11, tx=140.447, ty=-8.471},
        {fx=-144.604, fy=-19.511, to_zone=11, tx=244.542, ty=-60.040},
        {fx=-198.923, fy=-60.046, to_zone=11, tx=195.901, ty=-140.140},
        {fx=-259.934, fy=-120.907, to_zone=11, tx=99.852, ty=-155.918},
        {fx=-359.771, fy=-179.999, to_zone=11, tx=-5.107, ty=-219.906},
        {fx=454.912, fy=-19.355, to_zone=13, tx=-116.599, ty=-620.010},
        {fx=218.126, fy=187.428, to_zone=13, tx=-155.302, ty=500.121},
    },
    [13] = {
        {fx=-119.955, fy=-619.984, to_zone=12, tx=451.895, ty=-19.782},
        {fx=-158.309, fy=500.083, to_zone=12, tx=215.991, ty=185.113},
    },
    [16] = {
        {fx=180.000, fy=-19.992, to_zone=17, tx=-0.039, ty=-293.741},
    },
    [17] = {
        {fx=-0.013, fy=-295.991, to_zone=16, tx=179.973, ty=-23.145},
    },
    [18] = {
        {fx=20.000, fy=59.998, to_zone=19, tx=-0.039, ty=293.641},
    },
    [19] = {
        {fx=-0.013, fy=296.024, to_zone=18, tx=20.000, ty=63.031},
    },
    [20] = {
        {fx=100.000, fy=180.035, to_zone=21, tx=-0.039, ty=293.641},
    },
    [21] = {
        {fx=-0.013, fy=296.024, to_zone=20, tx=100.000, ty=183.068},
    },
    [22] = {
        {fx=-140.000, fy=-59.926, to_zone=23, tx=-0.039, ty=293.641},
    },
    [23] = {
        {fx=-0.013, fy=296.024, to_zone=22, tx=-140.000, ty=-56.893},
    },
    [24] = {
        {fx=-482.593, fy=283.523, to_zone=25, tx=567.624, ty=280.775},
        {fx=-600.989, fy=-100.086, to_zone=26, tx=7.425, ty=155.009},
        {fx=-401.488, fy=-219.958, to_zone=26, tx=13.659, ty=118.255},
    },
    [25] = {
        {fx=572.441, fy=282.673, to_zone=24, tx=-475.825, ty=281.149},
        {fx=602.537, fy=19.974, to_zone=26, tx=-46.465, ty=158.105},
        {fx=642.432, fy=-220.022, to_zone=26, tx=-37.079, ty=118.783},
        {fx=61.063, fy=739.997, to_zone=28, tx=-219.996, ty=82.795},
    },
    [26] = {
        {fx=9.902, fy=157.162, to_zone=24, tx=-596.494, ty=-99.420},
        {fx=16.108, fy=116.194, to_zone=24, tx=-398.021, ty=-220.780},
        {fx=-48.435, fy=159.972, to_zone=25, tx=599.205, ty=20.144},
        {fx=-39.224, fy=117.016, to_zone=25, tx=638.832, ty=-220.494},
        {fx=-0.034, fy=-41.987, to_zone=32, tx=600.101, ty=797.612},
        {fx=27.989, fy=57.053, to_zone=27, tx=260.020, ty=-290.461},
    },
    [27] = {
        {fx=259.967, fy=-293.412, to_zone=26, tx=27.971, ty=43.735},
    },
    [28] = {
        {fx=-220.082, fy=84.991, to_zone=25, tx=53.226, ty=739.997},
    },
    [32] = {
        {fx=599.803, fy=802.149, to_zone=26, tx=-0.173, ty=-39.706},
    },
    [33] = {
        {fx=0.068, fy=-439.247, to_zone=34, tx=-20.000, ty=-355.482},
        {fx=0.000, fy=723.119, to_zone=37, tx=580.000, ty=4.452},
    },
    [34] = {
        {fx=-20.000, fy=-364.277, to_zone=33, tx=0.000, ty=-464.781},
        {fx=10.000, fy=-320.000, to_zone=34, tx=-368.794, ty=260.000},
        {fx=-371.972, fy=260.000, to_zone=34, tx=-1.608, ty=-320.000},
        {fx=-20.000, fy=-271.805, to_zone=35, tx=-420.000, ty=243.491},
    },
    [35] = {
        {fx=-420.000, fy=235.712, to_zone=34, tx=-20.000, ty=-285.460},
        {fx=-484.739, fy=-340.000, to_zone=35, tx=-351.136, ty=-380.000},
        {fx=-355.149, fy=-380.141, to_zone=35, tx=-488.908, ty=-340.000},
        {fx=-478.374, fy=-339.977, to_zone=35, tx=-365.291, ty=-380.000},
        {fx=-361.598, fy=-380.000, to_zone=35, tx=-474.853, ty=-340.000},
        {fx=-361.604, fy=-340.000, to_zone=35, tx=-474.843, ty=-380.000},
        {fx=-478.375, fy=-380.000, to_zone=35, tx=-365.298, ty=-340.000},
        {fx=-355.157, fy=-340.000, to_zone=35, tx=-488.897, ty=-380.000},
        {fx=-484.729, fy=-380.000, to_zone=35, tx=-351.143, ty=-340.000},
        {fx=-460.000, fy=-446.305, to_zone=35, tx=-380.000, ty=-478.369},
        {fx=-380.000, fy=-473.733, to_zone=35, tx=-460.000, ty=-441.682},
        {fx=-460.000, fy=-473.733, to_zone=35, tx=-380.000, ty=-441.682},
        {fx=-380.000, fy=-446.305, to_zone=35, tx=-460.000, ty=-478.369},
    },
    [37] = {
        {fx=580.000, fy=-4.342, to_zone=33, tx=0.000, ty=718.112},
    },
    [48] = {
        {fx=-120.190, fy=67.981, to_zone=51, tx=610.542, ty=356.247},
        {fx=-68.008, fy=120.009, to_zone=52, tx=432.986, ty=-40.041},
        {fx=122.109, fy=40.005, to_zone=50, tx=-155.854, ty=-0.004},
        {fx=40.000, fy=-74.000, to_zone=48, tx=40.000, ty=-62.510},
    },
    [50] = {
        {fx=-158.102, fy=0.005, to_zone=48, tx=120.359, ty=40.004},
        {fx=-114.000, fy=-80.000, to_zone=50, tx=-102.500, ty=-80.000},
    },
    [51] = {
        {fx=440.032, fy=-100.039, to_zone=68, tx=356.503, ty=-179.607},
        {fx=99.428, fy=-146.551, to_zone=68, tx=20.007, ty=-116.515},
        {fx=-173.529, fy=-260.572, to_zone=68, tx=-51.776, ty=-225.531},
        {fx=-334.403, fy=-379.995, to_zone=68, tx=-196.824, ty=-420.565},
        {fx=60.017, fy=399.995, to_zone=68, tx=101.428, ty=151.549},
        {fx=-259.434, fy=306.498, to_zone=68, tx=-140.002, ty=118.503},
        {fx=-679.970, fy=-20.007, to_zone=68, tx=-408.475, ty=-139.983},
        {fx=-420.018, fy=-80.015, to_zone=68, tx=-220.786, ty=-149.674},
        {fx=-333.491, fy=-180.887, to_zone=68, tx=-204.826, ty=-259.893},
        {fx=-550.506, fy=-221.456, to_zone=68, tx=-354.967, ty=-260.010},
        {fx=614.376, fy=356.287, to_zone=48, tx=-118.150, ty=67.996},
        {fx=381.293, fy=440.795, to_zone=52, tx=299.997, ty=-27.998},
        {fx=-853.488, fy=99.990, to_zone=62, tx=119.515, ty=-379.987},
        {fx=-480.455, fy=-539.990, to_zone=65, tx=397.473, ty=-219.999},
        {fx=-739.064, fy=-569.553, to_zone=65, tx=220.001, ty=-81.496},
        {fx=-570.520, fy=-781.055, to_zone=65, tx=317.504, ty=-339.995},
    },
    [52] = {
        {fx=300.014, fy=-32.192, to_zone=51, tx=380.031, ty=435.510},
        {fx=439.985, fy=419.973, to_zone=68, tx=516.598, ty=459.890},
        {fx=120.986, fy=420.007, to_zone=68, tx=245.502, ty=499.935},
        {fx=437.971, fy=-40.006, to_zone=48, tx=-67.989, ty=118.151},
        {fx=-31.048, fy=-619.061, to_zone=65, tx=-117.491, ty=-299.997},
        {fx=-340.017, fy=-123.048, to_zone=65, tx=-459.995, ty=197.520},
        {fx=-41.055, fy=300.012, to_zone=62, tx=519.486, ty=260.008},
        {fx=-556.948, fy=99.990, to_zone=62, tx=-572.452, ty=-104.542},
        {fx=82.999, fy=620.022, to_zone=72, tx=325.000, ty=-620.000},
        {fx=-398.012, fy=20.005, to_zone=72, tx=-115.000, ty=-620.000},
        {fx=-100.006, fy=-476.957, to_zone=67, tx=340.383, ty=-157.447},
    },
    [53] = {
        {fx=42.910, fy=-24.006, to_zone=79, tx=25.965, ty=-700.009},
        {fx=16.000, fy=82.895, to_zone=79, tx=13.930, ty=-453.836},
        {fx=-42.911, fy=23.997, to_zone=79, tx=-260.961, ty=-699.985},
    },
    [54] = {
        {fx=499.997, fy=-43.502, to_zone=79, tx=140.007, ty=-40.736},
        {fx=603.978, fy=380.000, to_zone=79, tx=477.713, ty=139.990},
        {fx=-420.000, fy=-83.543, to_zone=79, tx=-499.999, ty=118.326},
        {fx=-419.995, fy=-565.494, to_zone=79, tx=-719.993, ty=-20.020},
        {fx=-420.008, fy=-276.433, to_zone=79, tx=-700.010, ty=121.777},
        {fx=-563.517, fy=379.970, to_zone=79, tx=-640.759, ty=339.955},
        {fx=-180.006, fy=-563.570, to_zone=57, tx=64.007, ty=-99.988},
    },
    [57] = {
        {fx=-43.034, fy=-260.010, to_zone=79, tx=-441.566, ty=-499.974},
        {fx=64.009, fy=-96.994, to_zone=54, tx=-180.028, ty=-559.987},
    },
    [61] = {
        {fx=901.279, fy=182.176, to_zone=62, tx=160.540, ty=139.988},
        {fx=659.804, fy=10.743, to_zone=62, tx=60.052, ty=118.482},
        {fx=340.889, fy=-105.180, to_zone=62, tx=-100.030, ty=-40.539},
        {fx=133.594, fy=99.840, to_zone=62, tx=-200.567, ty=100.001},
        {fx=-140.441, fy=-227.184, to_zone=62, tx=-340.028, ty=-200.503},
        {fx=-59.824, fy=293.319, to_zone=62, tx=-413.024, ty=385.630},
        {fx=-380.440, fy=304.699, to_zone=62, tx=-539.997, ty=400.551},
        {fx=-372.770, fy=-178.528, to_zone=62, tx=-599.423, ty=179.971},
        {fx=-461.086, fy=-269.248, to_zone=62, tx=-539.978, ty=79.533},
        {fx=-518.023, fy=59.959, to_zone=64, tx=-660.185, ty=-199.532},
        {fx=-514.716, fy=139.977, to_zone=64, tx=-660.012, ty=119.067},
        {fx=-19.543, fy=321.230, to_zone=72, tx=100.000, ty=-675.000},
    },
    [62] = {
        {fx=122.076, fy=-379.992, to_zone=51, tx=-848.503, ty=100.583},
        {fx=-19.996, fy=-442.020, to_zone=68, tx=-539.567, ty=-163.887},
        {fx=522.040, fy=260.010, to_zone=52, tx=-38.306, ty=300.018},
        {fx=-574.919, fy=-107.016, to_zone=52, tx=-559.439, ty=100.023},
        {fx=157.974, fy=140.047, to_zone=61, tx=897.992, ty=182.576},
        {fx=59.975, fy=121.036, to_zone=61, tx=657.948, ty=14.117},
        {fx=-99.974, fy=-38.030, to_zone=61, tx=341.609, ty=-101.977},
        {fx=-197.984, fy=99.981, to_zone=61, tx=136.983, ty=101.415},
        {fx=-340.027, fy=-198.010, to_zone=61, tx=-138.312, ty=-223.010},
        {fx=-411.154, fy=383.152, to_zone=61, tx=-58.721, ty=288.952},
        {fx=-539.989, fy=398.060, to_zone=61, tx=-381.807, ty=301.066},
        {fx=-601.957, fy=179.948, to_zone=61, tx=-376.457, ty=-177.608},
        {fx=-539.948, fy=81.993, to_zone=61, tx=-462.072, ty=-265.969},
    },
    [64] = {
        {fx=-660.555, fy=-203.192, to_zone=61, tx=-521.016, ty=60.013},
        {fx=-660.000, fy=123.071, to_zone=61, tx=-518.013, ty=139.972},
        {fx=378.162, fy=440.268, to_zone=61, tx=-518.013, ty=139.972},
        {fx=-21.948, fy=40.038, to_zone=61, tx=-518.013, ty=139.972},
        {fx=378.065, fy=-360.002, to_zone=61, tx=-518.013, ty=139.972},
    },
    [65] = {
        {fx=400.003, fy=-220.004, to_zone=51, tx=-475.452, ty=-539.960},
        {fx=220.003, fy=-78.990, to_zone=51, tx=-739.549, ty=-565.146},
        {fx=319.974, fy=-340.015, to_zone=51, tx=-565.517, ty=-780.596},
        {fx=-119.988, fy=-299.970, to_zone=52, tx=-33.517, ty=-619.263},
        {fx=-460.025, fy=200.007, to_zone=52, tx=-340.017, ty=-119.995},
    },
    [67] = {
        {fx=340.668, fy=-160.007, to_zone=52, tx=-100.000, ty=-479.514},
    },
    [68] = {
        {fx=359.961, fy=-179.998, to_zone=51, tx=444.495, ty=-99.976},
        {fx=20.016, fy=-120.017, to_zone=51, tx=99.049, ty=-150.954},
        {fx=-48.857, fy=-223.656, to_zone=51, tx=-168.529, ty=-260.803},
        {fx=-194.081, fy=-420.932, to_zone=51, tx=-328.495, ty=-379.397},
        {fx=101.075, fy=154.991, to_zone=51, tx=59.976, ty=404.470},
        {fx=-140.001, fy=122.003, to_zone=51, tx=-258.999, ty=311.538},
        {fx=-405.060, fy=-140.039, to_zone=51, tx=-675.497, ty=-19.657},
        {fx=-219.928, fy=-153.012, to_zone=51, tx=-419.293, ty=-84.475},
        {fx=-200.820, fy=-260.050, to_zone=51, tx=-328.534, ty=-180.819},
        {fx=-359.001, fy=-259.970, to_zone=51, tx=-555.517, ty=-220.201},
        {fx=519.935, fy=459.902, to_zone=52, tx=442.765, ty=419.999},
        {fx=242.450, fy=500.050, to_zone=52, tx=118.659, ty=419.999},
        {fx=-539.999, fy=-160.091, to_zone=62, tx=-20.007, ty=-439.514},
    },
    [72] = {
        {fx=-20.000, fy=840.000, to_zone=79, tx=339.996, ty=-721.286},
        {fx=320.000, fy=700.066, to_zone=79, tx=644.720, ty=219.989},
        {fx=-220.000, fy=480.000, to_zone=79, tx=-460.005, ty=-760.756},
        {fx=-520.000, fy=740.000, to_zone=79, tx=-360.759, ty=-300.035},
        {fx=-240.000, fy=220.000, to_zone=79, tx=-600.739, ty=-260.003},
        {fx=320.000, fy=-620.000, to_zone=52, tx=79.994, ty=619.974},
        {fx=-120.000, fy=-620.000, to_zone=52, tx=-401.065, ty=19.995},
        {fx=100.014, fy=-680.020, to_zone=61, tx=-19.867, ty=316.915},
    },
    [78] = {
        {fx=654.670, fy=-107.741, to_zone=79, tx=-539.996, ty=-559.207},
    },
    [79] = {
        {fx=22.439, fy=-700.082, to_zone=53, tx=40.658, ty=-24.001},
        {fx=10.539, fy=-454.895, to_zone=53, tx=15.999, ty=80.664},
        {fx=-257.573, fy=-699.995, to_zone=53, tx=-40.617, ty=24.000},
        {fx=140.076, fy=-37.471, to_zone=54, tx=500.019, ty=-40.026},
        {fx=474.546, fy=140.050, to_zone=54, tx=600.003, ty=379.997},
        {fx=-499.980, fy=121.517, to_zone=54, tx=-420.006, ty=-79.998},
        {fx=-717.074, fy=-20.004, to_zone=54, tx=-419.998, ty=-561.263},
        {fx=-699.982, fy=118.534, to_zone=54, tx=-419.998, ty=-279.996},
        {fx=-637.394, fy=339.974, to_zone=54, tx=-559.995, ty=380.002},
        {fx=-438.503, fy=-499.968, to_zone=57, tx=-39.998, ty=-260.182},
        {fx=340.005, fy=-724.025, to_zone=72, tx=-20.000, ty=835.000},
        {fx=641.578, fy=220.043, to_zone=72, tx=315.000, ty=700.000},
        {fx=-460.012, fy=-764.002, to_zone=72, tx=-220.000, ty=475.000},
        {fx=-357.507, fy=-300.011, to_zone=72, tx=-515.000, ty=740.000},
        {fx=-597.492, fy=-259.977, to_zone=72, tx=-235.000, ty=220.000},
        {fx=-539.987, fy=-556.030, to_zone=78, tx=652.174, ty=-104.920},
    },
    [80] = {
        {fx=113.458, fy=-57.351, to_zone=81, tx=86.131, ty=273.861},
        {fx=164.933, fy=164.792, to_zone=80, tx=162.591, ty=162.423},
    },
    [81] = {
        {fx=79.181, fy=280.841, to_zone=80, tx=103.978, ty=-47.951},
        {fx=706.187, fy=-591.226, to_zone=82, tx=-339.471, ty=462.074},
    },
    [82] = {
        {fx=-340.908, fy=465.750, to_zone=81, tx=693.068, ty=-590.713},
        {fx=591.936, fy=560.095, to_zone=84, tx=-439.393, ty=-239.958},
        {fx=625.783, fy=298.389, to_zone=83, tx=-393.238, ty=741.199},
        {fx=545.714, fy=-138.350, to_zone=83, tx=-579.977, ty=198.729},
        {fx=178.491, fy=-585.659, to_zone=83, tx=-661.000, ty=-328.000},
        {fx=-240.440, fy=-597.493, to_zone=85, tx=236.500, ty=20.000},
    },
    [83] = {
        {fx=-399.024, fy=740.117, to_zone=82, tx=621.865, ty=300.264},
        {fx=-580.330, fy=192.989, to_zone=82, tx=541.857, ty=-140.268},
        {fx=-660.000, fy=-322.995, to_zone=82, tx=180.335, ty=-581.766},
        {fx=243.803, fy=-579.216, to_zone=91, tx=-417.175, ty=337.204},
    },
    [84] = {
        {fx=-444.042, fy=-240.077, to_zone=82, tx=584.034, ty=558.296},
        {fx=479.834, fy=-358.198, to_zone=91, tx=-31.981, ty=611.327},
        {fx=-501.560, fy=508.768, to_zone=136, tx=17.331, ty=-654.230},
        {fx=167.076, fy=-407.071, to_zone=175, tx=420.035, ty=-119.510},
        {fx=162.950, fy=-605.297, to_zone=175, tx=436.613, ty=-300.015},
        {fx=87.122, fy=167.127, to_zone=175, tx=339.992, ty=321.016},
        {fx=-100.904, fy=19.082, to_zone=175, tx=59.989, ty=160.973},
        {fx=-247.087, fy=167.078, to_zone=175, tx=-160.776, ty=259.998},
        {fx=-259.112, fy=-99.116, to_zone=175, tx=-300.010, ty=119.191},
        {fx=-432.915, fy=367.091, to_zone=175, tx=-438.878, ty=540.004},
        {fx=-660.897, fy=140.929, to_zone=175, tx=-558.931, ty=99.999},
    },
    [85] = {
        {fx=240.000, fy=20.000, to_zone=82, tx=-199.971, ty=-497.938},
    },
    [87] = {
        {fx=-233.956, fy=105.000, to_zone=88, tx=380.038, ty=147.627},
        {fx=-150.750, fy=29.920, to_zone=87, tx=-177.000, ty=30.026},
        {fx=-150.750, fy=-30.329, to_zone=87, tx=-177.000, ty=-30.251},
    },
    [88] = {
        {fx=380.080, fy=144.116, to_zone=87, tx=-233.879, ty=94.000},
        {fx=-262.334, fy=574.413, to_zone=89, tx=-675.000, ty=-880.000},
    },
    [89] = {
        {fx=-680.000, fy=-880.000, to_zone=88, tx=-265.440, ty=572.308},
        {fx=489.490, fy=927.574, to_zone=90, tx=-219.445, ty=-490.542},
        {fx=759.208, fy=834.376, to_zone=90, tx=59.268, ty=-530.265},
    },
    [90] = {
        {fx=-216.311, fy=-494.094, to_zone=89, tx=495.063, ty=924.102},
        {fx=56.554, fy=-533.834, to_zone=89, tx=759.684, ty=829.356},
        {fx=582.492, fy=-377.871, to_zone=92, tx=-297.109, ty=96.002},
        {fx=551.257, fy=697.035, to_zone=91, tx=-102.210, ty=-917.643},
    },
    [91] = {
        {fx=-108.940, fy=-918.101, to_zone=90, tx=547.841, ty=696.323},
        {fx=-36.615, fy=616.612, to_zone=84, tx=479.218, ty=-354.065},
        {fx=367.707, fy=478.227, to_zone=98, tx=-454.218, ty=206.263},
        {fx=-381.995, fy=-791.740, to_zone=171, tx=380.617, ty=4.581},
        {fx=-792.229, fy=-502.043, to_zone=171, tx=84.741, ty=379.574},
        {fx=-419.567, fy=341.178, to_zone=83, tx=240.000, ty=-580.000},
    },
    [92] = {
        {fx=-300.088, fy=96.044, to_zone=90, tx=578.786, ty=-376.731},
    },
    [94] = {
        {fx=-40.194, fy=248.809, to_zone=95, tx=320.018, ty=-45.166},
        {fx=159.934, fy=-64.086, to_zone=94, tx=160.000, ty=-8.000},
    },
    [95] = {
        {fx=320.010, fy=-48.071, to_zone=94, tx=-39.996, ty=235.000},
        {fx=118.936, fy=648.841, to_zone=96, tx=-572.103, ty=-731.530},
    },
    [96] = {
        {fx=-576.178, fy=-733.593, to_zone=95, tx=120.000, ty=640.000},
        {fx=820.000, fy=121.000, to_zone=97, tx=540.000, ty=-599.000},
        {fx=101.981, fy=375.323, to_zone=97, tx=-614.041, ty=-416.260},
        {fx=141.722, fy=574.817, to_zone=97, tx=-654.060, ty=63.536},
        {fx=105.384, fy=781.756, to_zone=97, tx=-652.239, ty=213.951},
    },
    [97] = {
        {fx=540.000, fy=-602.000, to_zone=96, tx=820.000, ty=117.991},
        {fx=-614.879, fy=-419.435, to_zone=96, tx=97.017, ty=375.674},
        {fx=-654.638, fy=60.580, to_zone=96, tx=137.112, ty=575.659},
        {fx=-653.456, fy=217.250, to_zone=96, tx=103.991, ty=777.201},
        {fx=-454.593, fy=661.763, to_zone=98, tx=520.391, ty=-502.917},
        {fx=756.268, fy=-40.040, to_zone=99, tx=-239.447, ty=-19.980},
    },
    [98] = {
        {fx=519.887, fy=-507.899, to_zone=97, tx=-454.135, ty=657.790},
        {fx=-458.558, fy=205.424, to_zone=91, tx=363.430, ty=473.826},
        {fx=-104.001, fy=-427.826, to_zone=164, tx=-300.000, ty=157.000},
        {fx=263.991, fy=-390.048, to_zone=164, tx=100.000, ty=197.000},
    },
    [99] = {
        {fx=-242.002, fy=-20.019, to_zone=97, tx=730.000, ty=-40.000},
    },
    [100] = {
        {fx=-119.065, fy=280.921, to_zone=230, tx=-110.465, ty=-54.469},
        {fx=-157.666, fy=379.960, to_zone=231, tx=-248.893, ty=44.026},
        {fx=-11.697, fy=140.000, to_zone=101, tx=-16.472, ty=140.003},
        {fx=94.760, fy=-200.153, to_zone=101, tx=81.582, ty=-199.921},
        {fx=-740.570, fy=623.341, to_zone=140, tx=100.002, ty=-38.021},
        {fx=-177.516, fy=420.000, to_zone=231, tx=-234.393, ty=106.009},
        {fx=-560.415, fy=-613.176, to_zone=102, tx=-559.978, ty=680.592},
        {fx=-716.831, fy=18.192, to_zone=167, tx=-379.994, ty=-237.249},
    },
    [101] = {
        {fx=-30.050, fy=140.034, to_zone=100, tx=-24.427, ty=140.000},
        {fx=79.181, fy=280.841, to_zone=230, tx=110.234, ty=-54.223},
        {fx=56.140, fy=-199.961, to_zone=100, tx=83.913, ty=-200.033},
        {fx=199.982, fy=-544.574, to_zone=190, tx=-129.996, ty=256.499},
        {fx=661.624, fy=-595.631, to_zone=190, tx=57.415, ty=300.784},
        {fx=821.681, fy=666.443, to_zone=166, tx=-139.986, ty=-321.508},
    },
    [102] = {
        {fx=-558.569, fy=688.049, to_zone=100, tx=-559.963, ty=-602.479},
        {fx=801.831, fy=-37.618, to_zone=104, tx=-583.857, ty=-441.110},
        {fx=160.169, fy=-764.007, to_zone=103, tx=760.069, ty=409.269},
        {fx=-276.649, fy=99.618, to_zone=193, tx=-76.839, ty=659.969},
        {fx=-60.125, fy=148.001, to_zone=193, tx=179.906, ty=596.605},
        {fx=59.001, fy=-312.493, to_zone=193, tx=-200.326, ty=-219.847},
    },
    [103] = {
        {fx=919.212, fy=-440.003, to_zone=108, tx=-160.124, ty=883.812},
        {fx=758.323, fy=412.168, to_zone=102, tx=159.989, ty=-760.190},
        {fx=60.003, fy=-154.537, to_zone=248, tx=17.981, ty=99.830},
        {fx=-767.866, fy=18.376, to_zone=212, tx=280.502, ty=100.019},
    },
    [104] = {
        {fx=-599.998, fy=-440.077, to_zone=102, tx=795.118, ty=-39.978},
        {fx=591.936, fy=560.095, to_zone=105, tx=-439.393, ty=-239.958},
        {fx=-340.908, fy=465.750, to_zone=190, tx=242.012, ty=340.059},
        {fx=-240.440, fy=-597.493, to_zone=149, tx=218.468, ty=-3.871},
        {fx=344.389, fy=8.197, to_zone=2, tx=6.509, ty=-819.333},
        {fx=-538.898, fy=340.548, to_zone=2, tx=-419.796, ty=-554.553},
    },
    [105] = {
        {fx=-444.042, fy=-240.077, to_zone=104, tx=584.034, ty=558.296},
        {fx=479.955, fy=-363.913, to_zone=110, tx=-39.230, ty=635.328},
        {fx=491.918, fy=-159.982, to_zone=244, tx=-104.576, ty=187.365},
        {fx=-501.560, fy=508.768, to_zone=111, tx=17.331, ty=-654.230},
        {fx=-467.273, fy=332.724, to_zone=195, tx=-438.878, ty=540.004},
        {fx=-212.725, fy=132.695, to_zone=195, tx=-160.776, ty=259.998},
        {fx=52.695, fy=132.701, to_zone=195, tx=339.992, ty=321.016},
        {fx=-135.321, fy=-15.526, to_zone=195, tx=59.989, ty=160.973},
        {fx=-224.545, fy=-64.537, to_zone=195, tx=-300.010, ty=119.191},
        {fx=132.648, fy=-372.663, to_zone=195, tx=420.035, ty=-119.510},
        {fx=162.950, fy=-605.297, to_zone=195, tx=439.955, ty=-300.015},
        {fx=-695.363, fy=175.332, to_zone=195, tx=-558.931, ty=99.999},
    },
    [106] = {
        {fx=660.046, fy=302.725, to_zone=236, tx=142.002, ty=-2.008},
        {fx=0.735, fy=-79.065, to_zone=107, tx=0.840, ty=76.838},
        {fx=-440.639, fy=-276.308, to_zone=107, tx=-440.502, ty=-121.753},
        {fx=-518.828, fy=592.074, to_zone=108, tx=101.543, ty=-607.531},
        {fx=497.899, fy=1174.924, to_zone=143, tx=4.923, ty=59.551},
        {fx=-697.012, fy=311.829, to_zone=191, tx=2.871, ty=619.342},
        {fx=580.986, fy=695.899, to_zone=11, tx=-322.031, ty=-259.946},
        {fx=461.255, fy=736.063, to_zone=11, tx=-304.061, ty=-99.272},
    },
    [107] = {
        {fx=580.030, fy=-301.760, to_zone=234, tx=-16.039, ty=-132.804},
        {fx=260.000, fy=-180.000, to_zone=235, tx=-363.536, ty=-183.525},
        {fx=0.877, fy=80.156, to_zone=106, tx=0.020, ty=-75.405},
        {fx=-440.465, fy=-118.436, to_zone=106, tx=-440.792, ty=-272.901},
        {fx=-605.340, fy=-520.223, to_zone=191, tx=-4.025, ty=0.016},
    },
    [108] = {
        {fx=101.199, fy=-611.982, to_zone=106, tx=-518.867, ty=588.640},
        {fx=520.100, fy=752.858, to_zone=109, tx=-543.423, ty=-647.550},
        {fx=-160.469, fy=887.731, to_zone=103, tx=919.989, ty=-436.816},
        {fx=707.646, fy=217.545, to_zone=196, tx=45.982, ty=-340.094},
    },
    [109] = {
        {fx=-543.870, fy=-651.966, to_zone=108, tx=521.922, ty=747.850},
        {fx=551.257, fy=697.035, to_zone=110, tx=-117.506, ty=-920.604},
        {fx=582.492, fy=-377.871, to_zone=147, tx=-297.109, ty=96.002},
    },
    [110] = {
        {fx=-124.192, fy=-920.091, to_zone=109, tx=547.841, ty=696.323},
        {fx=-38.664, fy=640.092, to_zone=105, tx=479.744, ty=-359.840},
        {fx=376.860, fy=480.032, to_zone=120, tx=-475.679, ty=201.675},
        {fx=340.051, fy=613.388, to_zone=245, tx=-121.659, ty=-198.247},
        {fx=-381.995, fy=-791.740, to_zone=197, tx=380.617, ty=4.581},
        {fx=-792.229, fy=-502.043, to_zone=197, tx=84.741, ty=379.574},
    },
    [111] = {
        {fx=-542.044, fy=-378.674, to_zone=166, tx=302.778, ty=257.759},
        {fx=-251.957, fy=260.655, to_zone=112, tx=596.626, ty=-259.979},
        {fx=18.084, fy=-658.120, to_zone=105, tx=-500.451, ty=504.894},
        {fx=280.020, fy=571.937, to_zone=204, tx=-180.003, ty=-196.945},
        {fx=238.826, fy=-20.012, to_zone=9, tx=402.473, ty=-19.984},
        {fx=60.002, fy=-361.118, to_zone=9, tx=220.011, ty=-277.490},
        {fx=100.005, fy=161.199, to_zone=9, tx=179.977, ty=237.494},
        {fx=-201.163, fy=-219.982, to_zone=9, tx=-237.472, ty=-259.995},
        {fx=-19.975, fy=-38.825, to_zone=9, tx=-179.986, ty=-82.495},
        {fx=-339.952, fy=161.198, to_zone=9, tx=-299.995, ty=197.504},
    },
    [112] = {
        {fx=600.017, fy=-260.094, to_zone=111, tx=-247.911, ty=260.207},
        {fx=-437.021, fy=20.018, to_zone=161, tx=412.020, ty=-19.964},
        {fx=-131.779, fy=139.017, to_zone=5, tx=-300.004, ty=-603.122},
    },
    [113] = {
        {fx=-218.710, fy=-328.023, to_zone=174, tx=20.370, ty=275.782},
        {fx=239.925, fy=-180.056, to_zone=128, tx=45.250, ty=-140.562},
        {fx=319.969, fy=-59.997, to_zone=128, tx=-231.231, ty=-19.154},
        {fx=260.023, fy=440.024, to_zone=212, tx=-260.013, ty=-276.352},
        {fx=-290.939, fy=540.090, to_zone=201, tx=-399.541, ty=-420.000},
    },
    [114] = {
        {fx=499.979, fy=-79.972, to_zone=173, tx=-500.004, ty=0.358},
        {fx=260.282, fy=323.975, to_zone=125, tx=379.256, ty=-7.993},
        {fx=-325.066, fy=-99.662, to_zone=125, tx=-118.837, ty=-500.499},
        {fx=420.063, fy=194.874, to_zone=208, tx=940.000, ty=-357.759},
        {fx=20.049, fy=-325.004, to_zone=208, tx=700.001, ty=-688.183},
        {fx=129.980, fy=-20.014, to_zone=208, tx=618.389, ty=-380.008},
        {fx=85.052, fy=-99.867, to_zone=209, tx=-636.001, ty=-500.023},
    },
    [115] = {
        {fx=320.010, fy=-48.071, to_zone=238, tx=-39.996, ty=244.035},
        {fx=169.197, fy=-320.032, to_zone=240, tx=-244.532, ty=199.974},
        {fx=504.436, fy=133.854, to_zone=116, tx=-341.494, ty=106.469},
        {fx=425.197, fy=693.491, to_zone=116, tx=-422.940, ty=601.463},
        {fx=-374.546, fy=61.091, to_zone=145, tx=-100.050, ty=406.818},
        {fx=-279.160, fy=660.050, to_zone=194, tx=-316.779, ty=860.009},
        {fx=-340.006, fy=-399.521, to_zone=194, tx=-579.995, ty=-636.951},
        {fx=221.245, fy=39.306, to_zone=192, tx=-200.937, ty=59.994},
        {fx=-228.613, fy=-186.111, to_zone=146, tx=-259.648, ty=-358.869},
    },
    [116] = {
        {fx=-128.070, fy=-520.014, to_zone=241, tx=124.043, ty=-39.992},
        {fx=-343.926, fy=106.455, to_zone=115, tx=501.209, ty=134.432},
        {fx=-425.512, fy=600.890, to_zone=115, tx=421.970, ty=694.068},
        {fx=306.101, fy=664.733, to_zone=117, tx=-65.655, ty=-737.096},
        {fx=-60.020, fy=759.397, to_zone=194, tx=419.991, ty=716.991},
        {fx=399.294, fy=99.968, to_zone=192, tx=437.101, ty=180.014},
        {fx=259.996, fy=-479.060, to_zone=194, tx=580.018, ty=-637.011},
    },
    [117] = {
        {fx=-64.818, fy=-740.870, to_zone=116, tx=305.377, ty=660.435},
        {fx=-238.244, fy=703.991, to_zone=119, tx=-121.850, ty=-616.268},
        {fx=485.901, fy=514.729, to_zone=198, tx=-362.446, ty=-179.992},
        {fx=446.613, fy=-40.255, to_zone=118, tx=-620.614, ty=159.343},
    },
    [118] = {
        {fx=-625.802, fy=159.848, to_zone=117, tx=442.781, ty=-40.144},
        {fx=187.797, fy=-227.499, to_zone=249, tx=0.003, ty=117.971},
        {fx=-360.092, fy=315.477, to_zone=198, tx=474.629, ty=-259.091},
        {fx=444.135, fy=201.022, to_zone=213, tx=-58.808, ty=-286.654},
        {fx=-279.987, fy=-324.019, to_zone=4, tx=669.917, ty=911.655},
    },
    [119] = {
        {fx=-119.897, fy=-620.103, to_zone=117, tx=-239.016, ty=699.986},
        {fx=-454.593, fy=661.763, to_zone=120, tx=520.391, ty=-502.917},
        {fx=756.268, fy=-40.040, to_zone=151, tx=-239.447, ty=-19.980},
        {fx=774.883, fy=621.556, to_zone=121, tx=-459.974, ty=-480.899},
    },
    [120] = {
        {fx=519.887, fy=-507.899, to_zone=119, tx=-454.135, ty=657.790},
        {fx=-480.019, fy=200.836, to_zone=110, tx=372.582, ty=475.631},
        {fx=-579.985, fy=399.839, to_zone=246, tx=52.497, ty=-0.004},
        {fx=-104.001, fy=-427.826, to_zone=200, tx=-380.035, ty=398.032},
        {fx=263.991, fy=-390.048, to_zone=200, tx=19.991, ty=438.008},
    },
    [121] = {
        {fx=-459.975, fy=-483.827, to_zone=119, tx=772.487, ty=612.472},
        {fx=543.198, fy=-581.175, to_zone=153, tx=397.158, ty=-59.985},
        {fx=378.574, fy=-496.548, to_zone=153, tx=338.298, ty=75.195},
        {fx=177.189, fy=-181.773, to_zone=154, tx=118.378, ty=140.068},
        {fx=-240.008, fy=647.439, to_zone=122, tx=-0.012, ty=-146.430},
    },
    [122] = {
        {fx=-0.001, fy=-150.120, to_zone=121, tx=-238.888, ty=642.089},
        {fx=0.010, fy=126.633, to_zone=251, tx=-0.011, ty=-176.133},
    },
    [123] = {
        {fx=-241.934, fy=531.924, to_zone=250, tx=-51.997, ty=-106.254},
        {fx=-640.020, fy=-419.949, to_zone=176, tx=228.391, ty=335.129},
        {fx=120.004, fy=99.994, to_zone=124, tx=-357.024, ty=139.422},
        {fx=119.984, fy=19.983, to_zone=124, tx=-476.853, ty=59.442},
        {fx=119.993, fy=-299.975, to_zone=124, tx=-586.840, ty=-263.946},
        {fx=111.600, fy=-457.326, to_zone=124, tx=-476.878, ty=-500.774},
        {fx=420.025, fy=480.034, to_zone=205, tx=-418.664, ty=231.701},
    },
    [124] = {
        {fx=-360.018, fy=140.012, to_zone=123, tx=116.825, ty=100.000},
        {fx=-480.012, fy=59.973, to_zone=123, tx=116.805, ty=19.989},
        {fx=-589.975, fy=-263.321, to_zone=123, tx=116.813, ty=-299.969},
        {fx=-479.986, fy=-499.997, to_zone=123, tx=108.189, ty=-456.889},
        {fx=-102.098, fy=258.741, to_zone=205, tx=100.285, ty=-320.749},
        {fx=105.101, fy=345.912, to_zone=205, tx=299.938, ty=-81.802},
        {fx=299.955, fy=-627.151, to_zone=159, tx=179.986, ty=41.971},
        {fx=65.003, fy=-507.206, to_zone=159, tx=59.996, ty=81.988},
        {fx=7.971, fy=-507.240, to_zone=159, tx=-59.956, ty=81.957},
        {fx=347.445, fy=-225.017, to_zone=159, tx=238.951, ty=179.998},
        {fx=347.382, fy=-168.008, to_zone=159, tx=198.942, ty=300.020},
        {fx=380.022, fy=80.029, to_zone=160, tx=260.019, ty=319.871},
    },
    [125] = {
        {fx=378.677, fy=-12.103, to_zone=114, tx=260.090, ty=320.454},
        {fx=680.278, fy=-100.201, to_zone=173, tx=-519.361, ty=340.020},
        {fx=420.284, fy=363.912, to_zone=247, tx=-20.052, ty=-122.408},
        {fx=-114.443, fy=-500.360, to_zone=114, tx=-320.016, ty=-100.021},
        {fx=-19.832, fy=443.826, to_zone=174, tx=-20.008, ty=-242.030},
        {fx=179.942, fy=-285.087, to_zone=208, tx=179.993, ty=-147.950},
        {fx=-739.979, fy=-765.012, to_zone=208, tx=-740.014, ty=-521.835},
        {fx=-280.009, fy=299.985, to_zone=208, tx=-381.571, ty=859.998},
        {fx=-138.758, fy=-328.026, to_zone=208, tx=419.981, ty=-879.744},
        {fx=-329.071, fy=-221.287, to_zone=208, tx=-290.525, ty=-141.257},
        {fx=223.952, fy=12.711, to_zone=208, tx=327.608, ty=60.391},
        {fx=-19.983, fy=204.964, to_zone=208, tx=-59.994, ty=263.474},
        {fx=-848.505, fy=-541.019, to_zone=208, tx=-382.233, ty=-296.316},
        {fx=-888.021, fy=-421.232, to_zone=208, tx=-811.328, ty=-258.488},
        {fx=-375.969, fy=186.971, to_zone=208, tx=-583.626, ty=743.580},
        {fx=-492.829, fy=97.924, to_zone=208, tx=-341.118, ty=484.062},
    },
    [126] = {
        {fx=140.004, fy=-480.004, to_zone=246, tx=-158.194, ty=97.573},
        {fx=-642.015, fy=459.993, to_zone=127, tx=358.134, ty=-60.001},
        {fx=-289.882, fy=320.036, to_zone=184, tx=460.022, ty=-103.442},
    },
    [127] = {
        {fx=361.024, fy=-60.001, to_zone=126, tx=-638.714, ty=459.966},
    },
    [128] = {
        {fx=-239.077, fy=-19.953, to_zone=113, tx=315.644, ty=-60.633},
        {fx=39.951, fy=-140.068, to_zone=113, tx=230.879, ty=-180.868},
    },
    [130] = {
        {fx=0.001, fy=-106.589, to_zone=178, tx=-40.005, ty=-232.000},
        {fx=541.865, fy=176.066, to_zone=180, tx=189.849, ty=346.531},
        {fx=-94.809, fy=-145.489, to_zone=178, tx=-119.993, ty=-192.009},
        {fx=0.002, fy=569.781, to_zone=180, tx=-605.070, ty=436.136},
        {fx=94.793, fy=-145.478, to_zone=178, tx=119.987, ty=-191.989},
        {fx=-541.859, fy=176.056, to_zone=180, tx=60.080, ty=473.425},
        {fx=-91.502, fy=-433.740, to_zone=177, tx=-100.010, ty=-399.468},
        {fx=-334.886, fy=-460.949, to_zone=180, tx=-236.692, ty=413.546},
        {fx=91.486, fy=-433.753, to_zone=177, tx=99.981, ty=-399.453},
        {fx=-1.099, fy=-641.502, to_zone=251, tx=0.005, ty=362.018},
        {fx=359.114, fy=-242.838, to_zone=177, tx=359.501, ty=-260.017},
        {fx=317.283, fy=-103.073, to_zone=178, tx=351.996, ty=-160.002},
        {fx=433.233, fy=-14.592, to_zone=177, tx=399.460, ty=19.983},
        {fx=341.805, fy=266.383, to_zone=177, tx=319.465, ty=419.983},
        {fx=193.716, fy=266.626, to_zone=178, tx=239.998, ty=352.002},
        {fx=147.751, fy=407.505, to_zone=177, tx=139.982, ty=399.486},
        {fx=-147.737, fy=407.471, to_zone=177, tx=-140.018, ty=399.461},
        {fx=-195.491, fy=269.073, to_zone=178, tx=-240.003, ty=352.003},
        {fx=-341.805, fy=266.353, to_zone=177, tx=-320.485, ty=419.998},
        {fx=-433.420, fy=-14.597, to_zone=177, tx=-400.505, ty=19.998},
        {fx=-316.315, fy=-102.789, to_zone=178, tx=-351.995, ty=-159.991},
        {fx=-358.998, fy=-242.817, to_zone=177, tx=-360.460, ty=-260.002},
        {fx=334.888, fy=-460.958, to_zone=180, tx=527.721, ty=559.469},
    },
    [136] = {
        {fx=18.084, fy=-658.120, to_zone=84, tx=-500.451, ty=504.894},
        {fx=-180.000, fy=283.000, to_zone=137, tx=680.000, ty=-300.000},
    },
    [137] = {
        {fx=683.275, fy=-300.196, to_zone=136, tx=-180.000, ty=280.000},
        {fx=-437.021, fy=20.018, to_zone=138, tx=412.020, ty=-19.964},
    },
    [138] = {
        {fx=414.951, fy=-19.995, to_zone=137, tx=-414.000, ty=20.000},
        {fx=-185.026, fy=20.000, to_zone=155, tx=62.014, ty=-19.989},
    },
    [139] = {
        {fx=-540.003, fy=-209.995, to_zone=142, tx=439.814, ty=169.755},
        {fx=439.943, fy=69.988, to_zone=142, tx=437.235, ty=68.564},
    },
    [140] = {
        {fx=99.723, fy=-45.669, to_zone=100, tx=-738.178, ty=619.325},
        {fx=-7.915, fy=-60.877, to_zone=142, tx=-255.961, ty=-69.828},
        {fx=130.046, fy=181.572, to_zone=141, tx=-161.497, ty=19.985},
    },
    [141] = {
        {fx=-172.091, fy=16.925, to_zone=140, tx=125.852, ty=180.403},
        {fx=225.670, fy=18.620, to_zone=142, tx=276.235, ty=149.944},
        {fx=232.903, fy=101.886, to_zone=142, tx=295.374, ty=249.657},
        {fx=11.523, fy=-108.084, to_zone=142, tx=55.237, ty=70.061},
    },
    [142] = {
        {fx=273.019, fy=150.416, to_zone=141, tx=219.949, ty=19.489},
        {fx=291.230, fy=249.336, to_zone=141, tx=226.688, ty=101.045},
        {fx=50.504, fy=70.595, to_zone=141, tx=6.587, ty=-107.077},
        {fx=-251.344, fy=-69.672, to_zone=140, tx=-2.049, ty=-60.185},
        {fx=443.240, fy=169.684, to_zone=139, tx=-536.363, ty=-210.819},
        {fx=440.908, fy=69.949, to_zone=139, tx=444.270, ty=68.513},
    },
    [143] = {
        {fx=1.494, fy=59.893, to_zone=106, tx=495.999, ty=1172.910},
        {fx=117.365, fy=-140.074, to_zone=144, tx=-361.434, ty=-259.996},
        {fx=180.841, fy=-73.497, to_zone=144, tx=340.017, ty=277.484},
    },
    [144] = {
        {fx=-364.006, fy=-259.955, to_zone=143, tx=114.483, ty=-140.014},
        {fx=340.004, fy=280.002, to_zone=143, tx=180.861, ty=-70.971},
    },
    [145] = {
        {fx=-100.857, fy=411.410, to_zone=115, tx=-374.008, ty=63.289},
        {fx=-139.999, fy=-300.329, to_zone=146, tx=317.842, ty=380.143},
    },
    [146] = {
        {fx=321.741, fy=379.976, to_zone=145, tx=-135.904, ty=-300.668},
        {fx=-260.290, fy=-363.578, to_zone=115, tx=-225.921, ty=-185.284},
    },
    [147] = {
        {fx=-300.088, fy=96.044, to_zone=109, tx=578.786, ty=-376.731},
        {fx=384.501, fy=19.617, to_zone=148, tx=337.901, ty=20.087},
        {fx=260.002, fy=1.730, to_zone=148, tx=259.988, ty=42.943},
        {fx=-31.975, fy=59.829, to_zone=148, tx=2.887, ty=59.957},
    },
    [148] = {
        {fx=340.763, fy=20.085, to_zone=147, tx=387.382, ty=19.694},
        {fx=260.018, fy=40.049, to_zone=147, tx=259.988, ty=-0.811},
        {fx=-0.012, fy=60.009, to_zone=147, tx=-34.844, ty=59.775},
    },
    [149] = {
        {fx=219.470, fy=0.038, to_zone=104, tx=-239.556, ty=-591.281},
        {fx=279.002, fy=-18.078, to_zone=150, tx=261.354, ty=23.124},
        {fx=177.907, fy=-241.380, to_zone=150, tx=203.232, ty=-260.029},
        {fx=-22.126, fy=-82.941, to_zone=150, tx=-43.718, ty=-101.104},
        {fx=57.810, fy=-362.412, to_zone=150, tx=37.269, ty=-380.190},
        {fx=93.208, fy=-162.222, to_zone=150, tx=77.537, ty=-180.037},
    },
    [150] = {
        {fx=262.959, fy=19.936, to_zone=149, tx=282.292, ty=-17.908},
        {fx=200.040, fy=-260.230, to_zone=149, tx=177.745, ty=-238.573},
        {fx=-40.076, fy=-100.113, to_zone=149, tx=-22.086, ty=-80.150},
        {fx=40.040, fy=-380.068, to_zone=149, tx=57.952, ty=-359.422},
        {fx=79.993, fy=-180.071, to_zone=149, tx=93.179, ty=-158.973},
    },
    [151] = {
        {fx=-242.002, fy=-20.019, to_zone=119, tx=752.632, ty=-40.035},
        {fx=-165.505, fy=-140.027, to_zone=152, tx=-247.998, ty=-100.008},
        {fx=-295.090, fy=180.000, to_zone=152, tx=-288.028, ty=180.054},
    },
    [152] = {
        {fx=-244.926, fy=-100.000, to_zone=151, tx=-162.895, ty=-139.923},
        {fx=-285.039, fy=180.032, to_zone=151, tx=-292.009, ty=179.994},
    },
    [153] = {
        {fx=393.999, fy=-60.573, to_zone=121, tx=539.901, ty=-580.218},
        {fx=337.280, fy=71.739, to_zone=121, tx=380.081, ty=-499.802},
        {fx=-140.890, fy=206.980, to_zone=154, tx=-60.006, ty=-39.501},
        {fx=96.526, fy=-221.490, to_zone=202, tx=517.957, ty=540.045},
        {fx=8.902, fy=-338.835, to_zone=202, tx=-523.126, ty=-500.019},
    },
    [154] = {
        {fx=-60.006, fy=-42.501, to_zone=153, tx=-140.008, ty=202.715},
        {fx=121.480, fy=139.987, to_zone=121, tx=179.953, ty=-180.016},
    },
    [155] = {
        {fx=64.947, fy=-20.005, to_zone=138, tx=-181.969, ty=19.995},
        {fx=-559.607, fy=59.959, to_zone=156, tx=114.308, ty=0.022},
    },
    [156] = {
        {fx=117.118, fy=0.007, to_zone=155, tx=-555.996, ty=59.989},
    },
    [158] = {
        {fx=-300.039, fy=31.308, to_zone=158, tx=12.098, ty=27.683},
        {fx=19.967, fy=31.392, to_zone=158, tx=-291.555, ty=27.636},
        {fx=19.976, fy=31.373, to_zone=158, tx=251.863, ty=27.592},
        {fx=260.008, fy=31.337, to_zone=158, tx=27.719, ty=28.094},
    },
    [159] = {
        {fx=179.986, fy=44.575, to_zone=124, tx=299.997, ty=-622.998},
        {fx=60.015, fy=84.513, to_zone=124, tx=65.035, ty=-503.018},
        {fx=-59.978, fy=84.547, to_zone=124, tx=8.004, ty=-503.051},
        {fx=195.937, fy=300.014, to_zone=124, tx=343.003, ty=-168.009},
        {fx=235.933, fy=179.988, to_zone=124, tx=342.997, ty=-225.007},
        {fx=430.465, fy=213.312, to_zone=160, tx=460.003, ty=236.893},
        {fx=9.384, fy=13.077, to_zone=160, tx=20.019, ty=36.936},
        {fx=-230.897, fy=-106.535, to_zone=160, tx=-219.972, ty=-83.082},
        {fx=-13.745, fy=30.688, to_zone=160, tx=-36.018, ty=19.986},
        {fx=-230.364, fy=67.211, to_zone=163, tx=-363.970, ty=-341.473},
    },
    [160] = {
        {fx=459.971, fy=240.010, to_zone=159, tx=432.013, ty=216.472},
        {fx=19.987, fy=40.053, to_zone=159, tx=8.340, ty=15.884},
        {fx=-220.004, fy=-79.965, to_zone=159, tx=-231.602, ty=-103.515},
        {fx=-40.012, fy=20.044, to_zone=159, tx=-16.737, ty=31.905},
        {fx=-104.914, fy=55.960, to_zone=163, tx=316.848, ty=340.030},
        {fx=259.965, fy=323.041, to_zone=124, tx=380.798, ty=83.074},
        {fx=200.047, fy=-60.079, to_zone=211, tx=564.776, ty=500.819},
        {fx=179.971, fy=-160.013, to_zone=211, tx=-499.996, ty=-440.788},
    },
    [161] = {
        {fx=414.951, fy=-19.995, to_zone=112, tx=-433.249, ty=20.010},
        {fx=-185.026, fy=20.000, to_zone=162, tx=62.014, ty=-19.989},
    },
    [162] = {
        {fx=64.947, fy=-20.005, to_zone=161, tx=-181.969, ty=19.995},
        {fx=-559.607, fy=59.959, to_zone=165, tx=114.308, ty=0.022},
    },
    [163] = {
        {fx=-367.745, fy=-343.181, to_zone=159, tx=-231.701, ty=64.605},
        {fx=319.996, fy=340.015, to_zone=160, tx=-100.848, ty=55.405},
    },
    [164] = {
        {fx=-300.000, fy=160.000, to_zone=98, tx=-104.000, ty=-410.000},
        {fx=100.000, fy=200.000, to_zone=98, tx=264.000, ty=-370.000},
    },
    [165] = {
        {fx=117.118, fy=0.007, to_zone=162, tx=-555.996, ty=59.989},
    },
    [166] = {
        {fx=-140.044, fy=-324.570, to_zone=101, tx=818.507, ty=659.680},
        {fx=305.885, fy=258.022, to_zone=111, tx=-538.233, ty=-377.391},
    },
    [167] = {
        {fx=99.973, fy=75.035, to_zone=233, tx=14.872, ty=24.002},
        {fx=-379.996, fy=-239.562, to_zone=100, tx=-712.746, ty=18.408},
    },
    [168] = {
        {fx=-179.547, fy=-42.006, to_zone=208, tx=-980.193, ty=-282.863},
        {fx=184.919, fy=-100.041, to_zone=208, tx=-900.334, ty=-245.438},
    },
    [169] = {
        {fx=-340.011, fy=275.049, to_zone=192, tx=-259.996, ty=242.859},
        {fx=139.984, fy=132.962, to_zone=239, tx=-16.436, ty=255.546},
        {fx=-260.000, fy=85.825, to_zone=170, tx=-260.136, ty=-325.702},
        {fx=-323.996, fy=260.004, to_zone=170, tx=405.990, ty=420.062},
    },
    [170] = {
        {fx=-260.059, fy=-329.073, to_zone=169, tx=-259.980, ty=81.887},
        {fx=409.773, fy=419.936, to_zone=169, tx=-320.003, ty=260.022},
    },
    [171] = {
        {fx=380.064, fy=6.945, to_zone=91, tx=-376.179, ty=-776.159},
        {fx=87.469, fy=380.545, to_zone=91, tx=-774.920, ty=-494.912},
    },
    [172] = {
        {fx=23.039, fy=3.851, to_zone=234, tx=-193.484, ty=-21.772},
        {fx=-273.927, fy=-20.256, to_zone=173, tx=459.967, ty=160.627},
    },
    [173] = {
        {fx=459.979, fy=156.973, to_zone=172, tx=-270.707, ty=-20.268},
        {fx=-500.000, fy=4.001, to_zone=114, tx=499.839, ty=-76.809},
        {fx=-523.020, fy=340.048, to_zone=125, tx=676.280, ty=-99.425},
    },
    [174] = {
        {fx=-20.034, fy=-245.611, to_zone=125, tx=-19.901, ty=440.058},
        {fx=20.418, fy=280.014, to_zone=113, tx=-219.149, ty=-324.096},
    },
    [175] = {
        {fx=420.008, fy=-122.008, to_zone=84, tx=176.010, ty=-415.987},
        {fx=438.647, fy=-299.991, to_zone=84, tx=165.521, ty=-603.006},
        {fx=340.011, fy=324.996, to_zone=84, tx=96.010, ty=175.998},
        {fx=60.012, fy=164.979, to_zone=84, tx=-91.992, ty=28.006},
        {fx=-165.031, fy=260.003, to_zone=84, tx=-256.002, ty=176.001},
        {fx=-300.006, fy=115.014, to_zone=84, tx=-267.996, ty=-107.999},
        {fx=-434.959, fy=540.002, to_zone=84, tx=-424.004, ty=376.000},
        {fx=-555.012, fy=99.998, to_zone=84, tx=-652.004, ty=131.999},
    },
    [176] = {
        {fx=232.119, fy=337.806, to_zone=123, tx=-636.328, ty=-420.062},
        {fx=-60.563, fy=415.563, to_zone=252, tx=-19.238, ty=-63.964},
    },
    [177] = {
        {fx=-99.991, fy=-396.020, to_zone=130, tx=-90.952, ty=-431.084},
        {fx=100.000, fy=-396.005, to_zone=130, tx=90.945, ty=-431.105},
        {fx=356.044, fy=-260.000, to_zone=130, tx=356.155, ty=-240.876},
        {fx=396.003, fy=20.000, to_zone=130, tx=429.720, ty=-14.436},
        {fx=316.009, fy=420.000, to_zone=130, tx=339.137, ty=264.275},
        {fx=140.000, fy=396.016, to_zone=130, tx=146.516, ty=404.193},
        {fx=-140.000, fy=395.992, to_zone=130, tx=-146.537, ty=404.204},
        {fx=-315.995, fy=420.000, to_zone=130, tx=-339.163, ty=264.267},
        {fx=-396.015, fy=20.000, to_zone=130, tx=-430.705, ty=-14.479},
        {fx=-355.970, fy=-260.000, to_zone=130, tx=-356.137, ty=-240.902},
    },
    [178] = {
        {fx=-40.000, fy=-235.621, to_zone=130, tx=-0.003, ty=-112.182},
        {fx=-119.988, fy=-195.630, to_zone=130, tx=-96.318, ty=-147.817},
        {fx=119.993, fy=-195.610, to_zone=130, tx=96.326, ty=-147.828},
        {fx=355.705, fy=-159.993, to_zone=130, tx=320.798, ty=-104.233},
        {fx=239.985, fy=355.654, to_zone=130, tx=195.928, ty=269.686},
        {fx=-240.015, fy=355.655, to_zone=130, tx=-197.707, ty=272.111},
        {fx=-355.712, fy=-160.000, to_zone=130, tx=-319.884, ty=-103.948},
        {fx=-0.024, fy=60.008, to_zone=181, tx=-697.114, ty=-32.351},
    },
    [180] = {
        {fx=525.982, fy=561.904, to_zone=130, tx=333.017, ty=-458.350},
        {fx=186.966, fy=345.600, to_zone=130, tx=538.792, ty=175.066},
        {fx=-605.074, fy=433.148, to_zone=130, tx=-0.001, ty=566.523},
        {fx=62.905, fy=472.507, to_zone=130, tx=-538.786, ty=175.059},
        {fx=-234.934, fy=415.984, to_zone=130, tx=-332.991, ty=-458.311},
    },
    [181] = {
        {fx=-700.982, fy=-32.345, to_zone=178, tx=-3.380, ty=59.996},
    },
    [184] = {
        {fx=459.993, fy=-106.484, to_zone=126, tx=-286.271, ty=320.084},
    },
    [190] = {
        {fx=-130.011, fy=260.750, to_zone=101, tx=200.015, ty=-536.074},
        {fx=59.815, fy=305.710, to_zone=101, tx=660.078, ty=-588.047},
        {fx=250.585, fy=340.224, to_zone=104, tx=-339.471, ty=462.074},
    },
    [191] = {
        {fx=0.228, fy=-0.011, to_zone=107, tx=-601.433, ty=-520.031},
        {fx=7.124, fy=619.315, to_zone=106, tx=-694.542, ty=314.168},
    },
    [192] = {
        {fx=429.002, fy=180.000, to_zone=116, tx=396.225, ty=99.989},
        {fx=-193.007, fy=59.969, to_zone=115, tx=223.706, ty=39.976},
        {fx=-259.981, fy=250.063, to_zone=169, tx=-339.995, ty=278.013},
    },
    [193] = {
        {fx=-74.082, fy=659.997, to_zone=102, tx=-272.118, ty=98.859},
        {fx=180.034, fy=600.112, to_zone=102, tx=-59.413, ty=151.634},
        {fx=-203.476, fy=-219.995, to_zone=102, tx=60.020, ty=-316.183},
    },
    [194] = {
        {fx=-309.020, fy=860.021, to_zone=115, tx=-276.409, ty=660.009},
        {fx=420.018, fy=709.024, to_zone=116, tx=-59.996, ty=756.249},
        {fx=580.025, fy=-628.988, to_zone=116, tx=259.999, ty=-476.211},
        {fx=-579.994, fy=-629.016, to_zone=115, tx=-339.959, ty=-396.924},
    },
    [195] = {
        {fx=-555.012, fy=99.998, to_zone=105, tx=-693.609, ty=173.590},
        {fx=-434.959, fy=540.002, to_zone=105, tx=-464.853, ty=335.136},
        {fx=-165.031, fy=260.003, to_zone=105, tx=-214.550, ty=134.555},
        {fx=340.011, fy=324.996, to_zone=105, tx=54.594, ty=134.594},
        {fx=60.012, fy=164.979, to_zone=105, tx=-133.604, ty=-13.814},
        {fx=-300.006, fy=115.014, to_zone=105, tx=-226.393, ty=-66.378},
        {fx=420.008, fy=-122.008, to_zone=105, tx=134.402, ty=-374.405},
        {fx=441.989, fy=-299.991, to_zone=105, tx=165.521, ty=-603.006},
    },
    [196] = {
        {fx=44.028, fy=-340.120, to_zone=108, tx=703.532, ty=216.502},
        {fx=100.204, fy=-240.494, to_zone=11, tx=-372.562, ty=462.226},
    },
    [197] = {
        {fx=380.064, fy=6.945, to_zone=110, tx=-381.747, ty=-788.092},
        {fx=87.469, fy=380.545, to_zone=110, tx=-788.664, ty=-502.067},
    },
    [198] = {
        {fx=-370.004, fy=-180.822, to_zone=117, tx=481.394, ty=515.493},
        {fx=479.993, fy=-259.976, to_zone=118, tx=-356.219, ty=314.873},
        {fx=-140.331, fy=164.240, to_zone=7, tx=-163.496, ty=-260.872},
    },
    [200] = {
        {fx=-380.015, fy=400.996, to_zone=120, tx=-103.991, ty=-425.221},
        {fx=20.000, fy=440.979, to_zone=120, tx=264.002, ty=-387.444},
    },
    [201] = {
        {fx=-403.028, fy=-420.001, to_zone=113, tx=-294.009, ty=539.901},
    },
    [202] = {
        {fx=514.061, fy=539.258, to_zone=153, tx=93.262, ty=-220.303},
        {fx=-527.022, fy=-500.806, to_zone=153, tx=4.992, ty=-340.571},
    },
    [203] = {
        {fx=500.039, fy=519.998, to_zone=204, tx=99.980, ty=275.993},
        {fx=-453.019, fy=-399.995, to_zone=204, tx=241.998, ty=159.991},
    },
    [204] = {
        {fx=-179.993, fy=-199.963, to_zone=111, tx=280.025, ty=568.587},
        {fx=244.965, fy=59.998, to_zone=206, tx=-241.046, ty=19.991},
        {fx=264.944, fy=-70.021, to_zone=206, tx=-62.095, ty=-80.027},
        {fx=100.007, fy=280.023, to_zone=203, tx=499.993, ty=523.343},
        {fx=245.790, fy=159.982, to_zone=203, tx=-449.500, ty=-399.976},
    },
    [205] = {
        {fx=299.994, fy=-85.013, to_zone=124, tx=102.056, ty=344.135},
        {fx=100.340, fy=-323.961, to_zone=124, tx=-100.461, ty=255.806},
        {fx=-58.748, fy=110.261, to_zone=207, tx=-698.729, ty=-646.659},
        {fx=-419.271, fy=227.968, to_zone=123, tx=420.005, ty=476.787},
    },
    [206] = {
        {fx=-243.979, fy=19.998, to_zone=204, tx=242.074, ty=60.014},
        {fx=-65.027, fy=-80.020, to_zone=204, tx=262.011, ty=-69.998},
    },
    [207] = {
        {fx=-698.595, fy=-650.200, to_zone=205, tx=-60.296, ty=105.967},
    },
    [208] = {
        {fx=940.001, fy=-360.986, to_zone=114, tx=420.002, ty=191.739},
        {fx=700.015, fy=-685.018, to_zone=114, tx=19.980, ty=-321.526},
        {fx=180.010, fy=-145.070, to_zone=125, tx=179.988, ty=-281.511},
        {fx=-740.003, fy=-518.989, to_zone=125, tx=-740.000, ty=-761.537},
        {fx=614.981, fy=-379.983, to_zone=114, tx=126.597, ty=-20.012},
        {fx=420.065, fy=-883.002, to_zone=125, tx=-138.784, ty=-332.049},
        {fx=-286.968, fy=-141.236, to_zone=125, tx=-325.234, ty=-220.852},
        {fx=324.022, fy=60.323, to_zone=125, tx=220.071, ty=13.230},
        {fx=-59.992, fy=259.977, to_zone=125, tx=-20.001, ty=201.725},
        {fx=-376.956, fy=-297.505, to_zone=125, tx=-844.734, ty=-540.749},
        {fx=-806.639, fy=-259.527, to_zone=125, tx=-883.969, ty=-420.910},
        {fx=-587.853, fy=743.779, to_zone=125, tx=-379.069, ty=186.901},
        {fx=-344.133, fy=488.583, to_zone=125, tx=-492.920, ty=101.989},
        {fx=578.563, fy=-492.004, to_zone=209, tx=-580.383, ty=-563.956},
        {fx=-980.393, fy=-278.256, to_zone=168, tx=-177.804, ty=-37.893},
        {fx=-900.079, fy=-240.896, to_zone=168, tx=185.914, ty=-96.413},
        {fx=-384.968, fy=860.009, to_zone=125, tx=-283.003, ty=299.964},
    },
    [209] = {
        {fx=-580.924, fy=-567.951, to_zone=208, tx=577.033, ty=-496.000},
        {fx=-640.009, fy=-499.999, to_zone=114, tx=80.866, ty=-100.362},
    },
    [211] = {
        {fx=561.347, fy=499.999, to_zone=160, tx=196.421, ty=-60.319},
        {fx=-500.026, fy=-437.114, to_zone=160, tx=179.837, ty=-157.074},
    },
    [212] = {
        {fx=-260.017, fy=-280.011, to_zone=113, tx=260.398, ty=435.661},
        {fx=276.725, fy=99.985, to_zone=103, tx=-772.018, ty=19.101},
    },
    [213] = {
        {fx=-58.909, fy=-290.176, to_zone=118, tx=443.994, ty=198.161},
    },
    [230] = {
        {fx=113.458, fy=-57.351, to_zone=101, tx=86.131, ty=273.861},
        {fx=164.933, fy=164.792, to_zone=230, tx=162.591, ty=162.423},
        {fx=-113.372, fy=-57.418, to_zone=100, tx=-125.880, ty=274.100},
        {fx=0.013, fy=57.965, to_zone=231, tx=0.007, ty=-32.470},
    },
    [231] = {
        {fx=-0.107, fy=-36.133, to_zone=230, tx=-0.004, ty=54.388},
        {fx=-252.158, fy=43.913, to_zone=100, tx=-172.186, ty=379.998},
        {fx=134.995, fy=-8.439, to_zone=231, tx=132.764, ty=-6.178},
        {fx=-123.510, fy=270.516, to_zone=232, tx=-107.682, ty=-132.215},
        {fx=-238.702, fy=105.961, to_zone=100, tx=-180.473, ty=419.995},
        {fx=-123.566, fy=192.841, to_zone=2, tx=-479.621, ty=665.350},
    },
    [232] = {
        {fx=-111.802, fy=-136.498, to_zone=231, tx=-125.375, ty=268.640},
        {fx=83.260, fy=-139.282, to_zone=232, tx=79.362, ty=-135.450},
    },
    [233] = {
        {fx=12.495, fy=24.047, to_zone=167, tx=99.978, ty=72.867},
    },
    [234] = {
        {fx=-15.961, fy=-136.018, to_zone=107, tx=579.993, ty=-305.077},
        {fx=-104.080, fy=84.578, to_zone=235, tx=-201.904, ty=-194.828},
        {fx=-196.032, fy=-21.883, to_zone=172, tx=20.510, ty=4.019},
        {fx=121.831, fy=-71.955, to_zone=234, tx=116.899, ty=-71.987},
    },
    [235] = {
        {fx=-202.243, fy=-197.784, to_zone=234, tx=-104.018, ty=81.411},
        {fx=-233.956, fy=92.340, to_zone=236, tx=-194.012, ty=-76.239},
        {fx=-365.697, fy=-185.638, to_zone=107, tx=259.963, ty=-183.317},
        {fx=-211.990, fy=-0.046, to_zone=237, tx=-9.168, ty=0.001},
        {fx=-146.160, fy=29.920, to_zone=235, tx=-177.000, ty=30.026},
        {fx=-146.168, fy=-30.329, to_zone=235, tx=-177.000, ty=-30.251},
    },
    [236] = {
        {fx=150.300, fy=6.330, to_zone=106, tx=660.004, ty=306.236},
        {fx=-193.452, fy=-84.046, to_zone=235, tx=-233.879, ty=86.783},
        {fx=59.970, fy=-252.825, to_zone=236, tx=59.999, ty=-239.997},
    },
    [237] = {
        {fx=-6.175, fy=-0.008, to_zone=235, tx=-208.918, ty=0.020},
    },
    [238] = {
        {fx=-40.194, fy=248.809, to_zone=115, tx=320.018, ty=-45.166},
        {fx=-59.591, fy=-209.045, to_zone=240, tx=-117.255, ty=208.127},
        {fx=160.108, fy=60.360, to_zone=239, tx=-193.627, ty=140.505},
        {fx=159.934, fy=-64.086, to_zone=238, tx=159.978, ty=-61.890},
    },
    [239] = {
        {fx=-204.979, fy=139.551, to_zone=238, tx=153.460, ty=58.883},
        {fx=100.505, fy=-166.490, to_zone=241, tx=-50.641, ty=79.201},
        {fx=-18.340, fy=253.680, to_zone=169, tx=139.992, ty=130.492},
        {fx=-259.849, fy=-120.051, to_zone=239, tx=-256.780, ty=-119.973},
    },
    [240] = {
        {fx=-249.083, fy=199.980, to_zone=115, tx=166.612, ty=-319.972},
        {fx=-114.594, fy=215.791, to_zone=238, tx=-59.524, ty=-199.046},
        {fx=230.555, fy=179.926, to_zone=241, tx=-81.121, ty=-67.625},
        {fx=197.805, fy=264.495, to_zone=240, tx=197.711, ty=261.857},
    },
    [241] = {
        {fx=126.748, fy=-39.977, to_zone=116, tx=-125.638, ty=-520.000},
        {fx=-94.202, fy=-72.738, to_zone=240, tx=219.815, ty=176.514},
        {fx=-60.725, fy=91.983, to_zone=239, tx=99.772, ty=-154.266},
        {fx=-144.727, fy=40.005, to_zone=241, tx=-142.487, ty=40.007},
    },
    [243] = {
        {fx=-0.004, fy=-109.710, to_zone=244, tx=42.996, ty=-32.190},
        {fx=48.989, fy=-79.994, to_zone=243, tx=46.477, ty=-72.806},
    },
    [244] = {
        {fx=-106.095, fy=189.999, to_zone=105, tx=486.298, ty=-159.953},
        {fx=4.763, fy=-54.883, to_zone=245, tx=2.830, ty=57.689},
        {fx=46.000, fy=-30.915, to_zone=243, tx=-0.025, ty=-107.260},
        {fx=49.180, fy=-82.946, to_zone=244, tx=47.798, ty=-80.568},
    },
    [245] = {
        {fx=-123.065, fy=-200.691, to_zone=110, tx=339.741, ty=608.166},
        {fx=0.177, fy=59.589, to_zone=244, tx=7.042, ty=-53.100},
        {fx=29.694, fy=41.444, to_zone=246, tx=-150.730, ty=-19.900},
        {fx=43.944, fy=88.580, to_zone=245, tx=42.500, ty=86.074},
    },
    [246] = {
        {fx=54.979, fy=-0.019, to_zone=120, tx=-574.647, ty=399.974},
        {fx=-150.994, fy=-22.820, to_zone=245, tx=27.891, ty=42.423},
        {fx=-157.114, fy=100.055, to_zone=126, tx=139.997, ty=-476.956},
        {fx=-197.560, fy=0.005, to_zone=246, tx=-195.028, ty=0.008},
    },
    [247] = {
        {fx=-20.586, fy=-128.046, to_zone=125, tx=419.969, ty=359.802},
    },
    [248] = {
        {fx=16.895, fy=104.284, to_zone=103, tx=60.989, ty=-151.001},
    },
    [249] = {
        {fx=-0.179, fy=121.015, to_zone=118, tx=186.723, ty=-223.510},
    },
    [250] = {
        {fx=-50.004, fy=-111.502, to_zone=123, tx=-239.661, ty=528.069},
    },
    [251] = {
        {fx=0.004, fy=-180.057, to_zone=122, tx=-0.008, ty=123.478},
        {fx=0.000, fy=365.058, to_zone=130, tx=-1.122, ty=-638.232},
    },
    [252] = {
        {fx=-19.216, fy=-67.525, to_zone=176, tx=-60.566, ty=411.976},
    },
    [256] = {
        {fx=-160.300, fy=-26.000, to_zone=261, tx=431.000, ty=178.000},
        {fx=180.000, fy=-20.000, to_zone=257, tx=-150.000, ty=-20.000},
        {fx=74.000, fy=-148.000, to_zone=258, tx=-268.000, ty=-380.000},
        {fx=-76.000, fy=114.000, to_zone=258, tx=-612.000, ty=100.000},
        {fx=-4.500, fy=-146.000, to_zone=256, tx=-1.000, ty=-142.500},
        {fx=138.000, fy=4.000, to_zone=258, tx=-188.000, ty=60.000},
    },
    [257] = {
        {fx=-165.000, fy=-20.000, to_zone=256, tx=170.000, ty=-20.000},
        {fx=-122.000, fy=28.000, to_zone=258, tx=148.000, ty=140.000},
        {fx=-56.000, fy=-140.000, to_zone=257, tx=-56.000, ty=-128.500},
    },
    [258] = {
        {fx=-265.000, fy=-380.000, to_zone=256, tx=77.000, ty=-148.000},
        {fx=-615.000, fy=100.000, to_zone=256, tx=-76.000, ty=117.000},
        {fx=-185.000, fy=60.000, to_zone=256, tx=141.000, ty=4.000},
        {fx=145.000, fy=140.000, to_zone=257, tx=-126.000, ty=28.000},
        {fx=295.000, fy=-260.000, to_zone=257, tx=65.000, ty=-16.000},
    },
    [260] = {
        {fx=-379.572, fy=-446.000, to_zone=261, tx=-300.500, ty=400.000},
        {fx=-100.208, fy=-405.000, to_zone=261, tx=-20.000, ty=440.000},
        {fx=260.446, fy=-446.000, to_zone=261, tx=340.708, ty=359.000},
        {fx=-540.000, fy=-117.500, to_zone=269, tx=100.000, ty=-479.500},
        {fx=-117.000, fy=419.984, to_zone=269, tx=300.000, ty=-359.000},
    },
    [261] = {
        {fx=-299.713, fy=405.000, to_zone=260, tx=-379.759, ty=-441.000},
        {fx=-20.359, fy=445.000, to_zone=260, tx=-100.836, ty=-399.000},
        {fx=340.376, fy=364.000, to_zone=260, tx=260.044, ty=-441.000},
        {fx=-540.000, fy=-315.000, to_zone=268, tx=-260.000, ty=39.000},
        {fx=-99.891, fy=-527.175, to_zone=268, tx=-41.000, ty=-20.166},
        {fx=460.781, fy=176.941, to_zone=256, tx=-142.000, ty=-20.000},
    },
    [262] = {
        {fx=380.358, fy=462.210, to_zone=268, tx=-159.500, ty=-420.268},
        {fx=99.147, fy=-61.628, to_zone=268, tx=-299.849, ty=-438.154},
        {fx=-360.061, fy=305.120, to_zone=272, tx=120.000, ty=380.000},
        {fx=-460.977, fy=-302.508, to_zone=272, tx=60.000, ty=80.000},
    },
    [263] = {
        {fx=235.000, fy=59.500, to_zone=270, tx=200.500, ty=220.032},
        {fx=-405.000, fy=259.500, to_zone=273, tx=480.500, ty=140.000},
    },
    [265] = {
        {fx=580.000, fy=-482.000, to_zone=269, tx=100.000, ty=121.000},
        {fx=-540.000, fy=-405.000, to_zone=273, tx=500.000, ty=400.500},
    },
    [266] = {
        {fx=445.000, fy=299.000, to_zone=272, tx=-320.500, ty=340.000},
        {fx=-501.000, fy=325.000, to_zone=273, tx=180.000, ty=40.500},
    },
    [267] = {
        {fx=500.500, fy=-483.000, to_zone=273, tx=340.000, ty=520.500},
    },
    [268] = {
        {fx=-36.500, fy=-19.748, to_zone=261, tx=-100.000, ty=-521.955},
        {fx=-260.000, fy=43.000, to_zone=261, tx=-540.319, ty=-320.000},
        {fx=-164.078, fy=-420.772, to_zone=262, tx=374.347, ty=460.167},
        {fx=-299.669, fy=-443.428, to_zone=262, tx=99.563, ty=-66.515},
        {fx=-501.283, fy=4.197, to_zone=270, tx=420.000, ty=-280.500},
    },
    [269] = {
        {fx=99.500, fy=116.000, to_zone=265, tx=580.522, ty=-477.705},
        {fx=300.000, fy=-364.000, to_zone=260, tx=-121.000, ty=420.000},
        {fx=100.500, fy=-484.500, to_zone=260, tx=-540.076, ty=-121.519},
        {fx=-126.260, fy=-381.551, to_zone=270, tx=520.000, ty=419.832},
    },
    [270] = {
        {fx=-219.784, fy=524.000, to_zone=273, tx=400.500, ty=100.000},
        {fx=527.531, fy=418.559, to_zone=269, tx=-120.923, ty=-380.194},
        {fx=-180.217, fy=-321.000, to_zone=272, tx=60.000, ty=520.000},
        {fx=419.000, fy=-286.000, to_zone=268, tx=-500.388, ty=-0.261},
        {fx=207.632, fy=217.938, to_zone=263, tx=240.000, ty=59.500},
    },
    [272] = {
        {fx=60.000, fy=85.000, to_zone=262, tx=-455.880, ty=-300.683},
        {fx=125.000, fy=380.000, to_zone=262, tx=-355.480, ty=301.098},
        {fx=-325.000, fy=340.000, to_zone=266, tx=440.000, ty=300.000},
        {fx=60.000, fy=525.000, to_zone=270, tx=-179.418, ty=-315.152},
    },
    [273] = {
        {fx=500.000, fy=404.000, to_zone=265, tx=-540.237, ty=-399.500},
        {fx=484.000, fy=140.000, to_zone=263, tx=-400.000, ty=260.000},
        {fx=180.000, fy=37.000, to_zone=266, tx=-500.000, ty=320.000},
        {fx=404.000, fy=100.000, to_zone=270, tx=-219.869, ty=519.000},
        {fx=340.000, fy=524.000, to_zone=267, tx=500.500, ty=-479.500},
    },
    [281] = {
        {fx=19.355, fy=-43.000, to_zone=267, tx=-212.000, ty=-414.000},
    },
}

-- Resolve a zone name to a zone ID.
-- Accepts:
--   plain text name ("Port Bastok")
--   pipe-wrapped name ("|Port Bastok|")
--   raw autotranslate bytes from e.command: \xFD\x02\x??\x{group}\x{msg}\xFD
--     where group is at byte offset 4 and msg at byte offset 5 from the start
-- Returns zone_id or nil if not found.
function M.resolve_zone(name)
    if name == nil then return nil end
    -- Detect raw autotranslate byte sequence (starts with 0xFD)
    if name:byte(1) == 0xFD then
        local group = name:byte(4)
        local msg   = name:byte(5)
        if group ~= nil and msg ~= nil then
            return M.AT_LOOKUP[group * 256 + msg]
        end
        return nil
    end
    -- Strip pipe-wrapped display format (|Zone Name|)
    name = name:match('^|(.+)|$') or name
    -- Normalise: lowercase, remove apostrophes
    local key = name:lower():gsub("'", "")
    return M.ZONE_IDS[key]
end

-- Return the list of exits from a zone (or empty table).
function M.get_exits(zone_id)
    return M.EXITS[zone_id] or {}
end

-- Zone-level Dijkstra — find a sequence of zone transitions from from_zone to
-- to_zone.  start_x/start_y are the player's current position in from_zone
-- (defaults to 0,0 if omitted).
--
-- Edge cost = Euclidean distance walked across each zone (from the entry
-- point to the chosen exit).  This causes the planner to prefer routes where
-- entry and exit within each intermediate zone are geometrically close,
-- naturally avoiding routes that require crossing an impassable wall.
--
-- Returns a list of transition records { from_zone, fx, fy, to_zone, tx, ty }
-- or nil if no path exists.
-- step_cost_fn is an optional function: step_cost_fn(zone_id, from_x, from_y, exit)
--   Returns the cost (number) of walking from (from_x, from_y) to exit.fx/fy
--   within zone_id, or nil if that exit is unreachable from that position.
--   When nil is returned the exit is skipped entirely — this is how navmesh
--   walls are communicated to the planner.
--   When step_cost_fn is not provided, falls back to plain Euclidean distance
--   (no wall detection).
function M.zone_astar(from_zone, to_zone, start_x, start_y, step_cost_fn)
    if from_zone == to_zone then return {} end

    start_x = start_x or 0
    start_y = start_y or 0

    -- State key encodes zone + the specific entry position so multiple
    -- entrances to the same zone are treated as distinct states.
    local function skey(zone, x, y)
        return string.format('%d:%.2f:%.2f', zone, x, y)
    end

    local start_key = skey(from_zone, start_x, start_y)
    local best      = { [start_key] = 0 }   -- best cost to each state
    local prev      = {}                     -- prev[key] = { transition, parent_key }
    local visited   = {}
    local open      = { { key=start_key, zone=from_zone, x=start_x, y=start_y, cost=0 } }

    while #open > 0 do
        table.sort(open, function(a, b) return a.cost < b.cost end)
        local cur = table.remove(open, 1)

        if visited[cur.key] then goto continue end
        visited[cur.key] = true

        if cur.zone == to_zone then
            -- Reconstruct path
            local path = {}
            local k = cur.key
            while prev[k] do
                local entry = prev[k]
                table.insert(path, 1, entry.transition)
                k = entry.parent_key
            end
            return path
        end

        for _, exit in ipairs(M.get_exits(cur.zone)) do
            local nkey     = skey(exit.to_zone, exit.tx, exit.ty)
            local step_cost
            if step_cost_fn then
                step_cost = step_cost_fn(cur.zone, cur.x, cur.y, exit)
                if step_cost == nil then goto skip_exit end  -- unreachable per navmesh
            else
                local dx = exit.fx - cur.x
                local dy = exit.fy - cur.y
                step_cost = math.sqrt(dx*dx + dy*dy)
            end
            local new_cost = cur.cost + step_cost

            if not visited[nkey] and (best[nkey] == nil or new_cost < best[nkey]) then
                best[nkey] = new_cost
                prev[nkey] = {
                    transition = {
                        from_zone = cur.zone,
                        fx = exit.fx, fy = exit.fy,
                        to_zone   = exit.to_zone,
                        tx = exit.tx, ty = exit.ty,
                    },
                    parent_key = cur.key,
                }
                local found = false
                for _, e in ipairs(open) do
                    if e.key == nkey then
                        e.cost = new_cost
                        found = true
                        break
                    end
                end
                if not found then
                    table.insert(open, {
                        key  = nkey,
                        zone = exit.to_zone,
                        x    = exit.tx, y = exit.ty,
                        cost = new_cost,
                    })
                end
            end

            ::skip_exit::
        end

        ::continue::
    end

    return nil
end

return M
